/* All site content lives here. Edit this file to change text, links, projects, notes and the shelf. */
window.CONTENT = {
  person: {
    name: "Adya Srivastava",
    line: "I research how language models solve problems, and build the ML systems around them.",
    proof: ["Paper at CAISc 2026", "Ex-ML Engineer, Nurix AI", "National winner, Citi Innovation Challenge"],
    status: "Open to ML research and research engineering roles",
    email: "srivastavadya@gmail.com",
    github: "https://github.com/Adya6714",
    linkedin: "https://www.linkedin.com/in/adyasri",
    openreview: "https://openreview.net/forum?id=d8w4gMVQ1w",
    about: "BITS Pilani graduate (Electrical and Electronics, minor in Finance, 2026). I like questions where the benchmark number is not the whole story: whether a model computed or recalled, whether its confidence means anything, whether a result survives a change that should not matter. I'm looking for a team that works on hard versions of those questions."
  },

  papers: [
    { title: "Same Score, Different Strategy", status: "CAISc 2026", kind: "published",
      note: "Multi-probe diagnosis of structural fragility in LLM reasoning.",
      links: [["Paper", "https://openreview.net/forum?id=d8w4gMVQ1w"], ["Project page", "https://adya6714.github.io/retrieval-vs-computation/"], ["Code", "https://github.com/Adya6714/retrieval-vs-computation"]] },
    { title: "Reading Without Looking", status: "Preprint", kind: "preprint",
      note: "Does OCR confidence track visual evidence? A controlled study on Indic scripts.",
      links: [["Project page", "https://adya6714.github.io/vlm-ocr-eval/"], ["PDF", "https://adya6714.github.io/vlm-ocr-eval/paper/main.pdf"], ["Code", "https://github.com/Adya6714/vlm-ocr-eval"]] },
    { title: "Diffusion-Generated Volatility Surfaces for RL Hedging of NIFTY 50 Barrier Options", status: "Draft", kind: "draft",
      note: "A model-risk decomposition of RL hedging trained on generated market data.",
      links: [["Draft PDF", "https://drive.google.com/file/d/1eXAm7XeUYIWnzu_3MWRpSY6nO9gyGDNV/view?usp=drive_link"], ["Code", "https://github.com/Adya6714/ddpm-vol-hedging"]] },
    { title: "Hybrid Quantum-Classical Paradigms for Nonlinear Dynamics, ML and Autonomous Systems", status: "Survey", kind: "survey",
      note: "Carleman linearization, variational algorithms for PDEs, quantum RL, hardware comparisons.",
      links: [["PDF", "https://drive.google.com/file/d/1zwhnW2Nvl6I5myx556UoGED-1MKv9qt5/view?usp=sharing"]] },
    { title: "Retrieval vs Computation, papers 2 to 4", status: "Planned", kind: "planned",
      note: "Where the split lives inside the network, which training conditions produce it, and how it changes across scale.",
      links: [] }
  ],

  notes: [
    { id: "n-rename", title: "A rename erased a perfect score", headline: "o3-mini: 1.00 to 0.00 after a rename", project: "Retrieval vs Computation",
      q: "Does a model that solves a problem perfectly still solve it when only the names change?",
      found: "On weighted interval scheduling, o3-mini scored a perfect 1.00 on the original problems and 0.00 after the entities were renamed. Every model that solved this subtype at all collapsed under the rename. Exposure and difficulty move together on this subtype, so this result alone cannot say which one is responsible.",
      why: "A benchmark would have reported this model as fully capable on the task. The rename shows the capability did not survive a change that leaves the problem identical.",
      link: ["Read the paper", "https://openreview.net/forum?id=d8w4gMVQ1w"] },
    { id: "n-spread", title: "One rename, very different effects", headline: "Same change, opposite directions across models", project: "Retrieval vs Computation",
      q: "If models simply recall memorised problems, shouldn't a rename hurt them all in the same way?",
      found: "The same rename helped three models substantially, left two at the floor, and even reversed direction across problem subtypes. On arithmetic, Gemini stayed steady when the numbers were regenerated (0.909 to 0.958) but fell to 0.523 when only the names changed.",
      why: "That spread is hard to explain with one shared retrieval mechanism. It points to model-specific strategies hiding under similar scores.",
      link: ["Project page", "https://adya6714.github.io/retrieval-vs-computation/"] },
    { id: "n-inject", title: "Accepting a wrong step is not derailing", headline: "88 to 100% accept an injected error, yet still finish", project: "Retrieval vs Computation",
      q: "If a model accepts a wrong intermediate value, does its answer go wrong too?",
      found: "When I injected an incorrect state mid-solve, compliant models accepted it 88 to 100% of the time. Accuracy after injection stayed close to uninterrupted performance (Claude 52.5%, GPT-4o 50.8%, o3-mini 37.7%), and whether a model complied did not predict whether it finished correctly.",
      why: "Following an injected value is not evidence that a model reasons from its own steps. Compliance and derailment have to be measured separately.",
      link: ["Read the paper", "https://openreview.net/forum?id=d8w4gMVQ1w"] },
    { id: "n-ambig", title: "Most instances stay ambiguous", headline: "61.6% of instances resist a clean label", project: "Retrieval vs Computation",
      q: "Can three behavioural probes label each problem as retrieved or computed?",
      found: "Combining the probes into a per-instance label sounds like the goal. Under strict thresholds, 61.6% of instances stayed ambiguous, so the labels work as calibration points rather than a verdict.",
      why: "It sets an honest bar for the next papers: per-instance diagnosis needs instruments validated beyond behaviour, which is where the mechanism work starts.",
      link: ["Read the paper", "https://openreview.net/forum?id=d8w4gMVQ1w"] },
    { id: "n-harness", title: "My harness caught my own bugs", headline: "Gold in, gold out, before any result", project: "Retrieval vs Computation",
      q: "How do you know a probe measures the model and not your own verifier?",
      found: "Every probe was checked gold in, gold out: feed the verifier known-correct answers and confirm they score as correct. Those checks caught several verifier bugs in my own pipeline before they reached the results.",
      why: "Behavioural probes are fragile instruments. Checking the instrument is part of the experiment, not cleanup.",
      link: ["Code and audit", "https://github.com/Adya6714/retrieval-vs-computation"] },
    { id: "n-pos0", title: "90% confident, almost never right", headline: "Confidence 0.90, correct answer ~10⁻¹¹", project: "Reading Without Looking",
      q: "When an OCR model says it is 90% sure, is that about the image?",
      found: "At the first character, where no earlier text can help, my OCR model reported about 0.90 confidence while the correct character had roughly 2×10⁻¹¹ probability. It was the top choice 0 times in 180 evaluations.",
      why: "Confidence measured how peaked the output was, not whether the image supported the answer.",
      link: ["Project page", "https://adya6714.github.io/vlm-ocr-eval/"] },
    { id: "n-blank", title: "A blank page gets the same confidence", headline: "Text 0.994, blank page 0.990", project: "Reading Without Looking",
      q: "If confidence depends on vision, removing the image should lower it. Does it?",
      found: "Blank, noise and scrambled images barely moved confidence (0.994 for text against 0.990 for a blank page). Switching off the vision pathway changed about 8% of predictions while confidence stayed almost flat.",
      why: "A routing system that trusts confidence would wave exactly these pages through.",
      link: ["Project page", "https://adya6714.github.io/vlm-ocr-eval/"] },
    { id: "n-auroc", title: "Good AUROC can still mislead", headline: "AUROC 0.84 in-sample, 0.57 held out", project: "Reading Without Looking",
      q: "Is confidence useful for separating right from wrong answers?",
      found: "On familiar lines, confidence separated right from wrong reasonably well (AUROC 0.838). On held-out lines it dropped to about 0.57, with a calibration error of 0.811.",
      why: "A meter that looks good in-sample can be close to useless for decisions on new pages. Held-out checks have to come before any routing claim.",
      link: ["Project page", "https://adya6714.github.io/vlm-ocr-eval/"] }
  ],

  projects: [
    { id: "p-rvc", title: "Retrieval vs Computation", group: ["Research"], demo: "rvc",
      line: "A measurement toolkit for telling whether an LLM reasoned or recalled.",
      chips: ["LLM evaluation", "Reasoning", "Robustness"],
      problem: "Benchmarks say whether an answer is right, not how the model got there. Two models with the same score can fail in very different ways once deployed.",
      built: ["Three probes: rewording and renaming, plan-versus-execution consistency, and closeness to training data.", "219 problems across arithmetic, planning and optimisation, run on five models (about 20,000 API calls), with exact checkers for every answer.", "A reproducible pipeline: raw runs, derived metrics, paper tables and tests all regenerate from code."],
      impact: "Gives teams a way to judge which models to trust on unseen problems, not just which score highest. Phase one of a four-paper program on where retrieval and computation split inside LLMs.",
      links: [["Site", "https://adya6714.github.io/retrieval-vs-computation/"], ["Code", "https://github.com/Adya6714/retrieval-vs-computation"], ["Paper", "https://openreview.net/forum?id=d8w4gMVQ1w"]] },
    { id: "p-ocr", title: "Reading Without Looking", group: ["Research"], demo: "ocr",
      line: "Can you trust OCR confidence on Indic scripts?",
      chips: ["Vision-language", "Calibration", "Indic OCR"],
      problem: "Document systems auto-accept pages with high confidence and send the rest to people. That only works if confidence tracks what the model actually sees, and Indic scripts make this hard to measure.",
      built: ["Grapheme-level scoring and a HarfBuzz renderer that produces real Indic script shaping.", "A 19.6M-parameter OCR model trained from scratch, so every internal step can be inspected.", "Counterfactual probes an API cannot run (blank, noise and scrambled images, removing the vision pathway), plus a transfer test on a production OCR API with pre-registered statistics."],
      impact: "Shows peak confidence can stay high while the image contributes almost nothing, so routing on it alone can fail. Proposes grounding-aware confidence instead.",
      links: [["Site", "https://adya6714.github.io/vlm-ocr-eval/"], ["Code", "https://github.com/Adya6714/vlm-ocr-eval"], ["Preprint", "https://adya6714.github.io/vlm-ocr-eval/paper/main.pdf"]] },
    { id: "p-ddpm", title: "Synthetic Volatility Surfaces for Hedging", group: ["Research", "Quant"], demo: "ddpm",
      line: "Diffusion-generated NIFTY 50 volatility surfaces to train an RL hedging agent.",
      chips: ["Diffusion models", "Reinforcement learning", "Quant"],
      problem: "Training a hedging agent needs far more market scenarios than history provides, and an agent trained on one model of the market inherits that model's blind spots.",
      built: ["A dataset of 1,268 NIFTY implied volatility surfaces (2018 to 2026) built from 912K+ NSE option rows.", "A conditional diffusion model that generates new surfaces with fewer arbitrage violations than market data (penalty 0.005 vs 0.009).", "A PPO hedging agent for barrier options, compared against a Heston-trained RL baseline."],
      impact: "Cut tail-risk hedging error (CVaR 95%) by 60.1% against Black-Scholes, and separates how much of the result comes from the generator versus the agent.",
      links: [["Code", "https://github.com/Adya6714/ddpm-vol-hedging"], ["Draft", "https://drive.google.com/file/d/1eXAm7XeUYIWnzu_3MWRpSY6nO9gyGDNV/view?usp=drive_link"]] },
    { id: "p-mesh", title: "OmniMesh", group: ["Agents & systems"],
      line: "An offline disaster-response network with an AI triage backend.",
      chips: ["Multi-agent", "LLM serving", "Edge"],
      problem: "In disasters, internet and cell networks fail first, exactly when responders need to coordinate and triage.",
      built: ["Android phones act as triage nodes in an offline-first, peer-to-peer mesh.", "A six-agent FastAPI backend serving Gemma-2-9B with vLLM on an AMD GPU.", "Sync to the cloud once connectivity returns."],
      impact: "Keeps communication and decision support working when infrastructure is down. Built for the AMD Developer Hackathon ACT II and entered in the Google Solution Challenge 2025.",
      links: [["Code", "https://github.com/Adya6714/OmniMesh"]] },
    { id: "p-cw", title: "CloudWatch in Plain English", group: ["Agents & systems"],
      line: "Ask AWS metrics questions in natural language and get charts back.",
      chips: ["Agents", "Semantic search", "AWS"],
      problem: "Finding the right CloudWatch metric means knowing its exact name and digging through the console or CLI.",
      built: ["A Bedrock agent describes every metric; descriptions become embeddings stored in S3 with metadata in DynamoDB, refreshed weekly.", "Queries are embedded and matched by cosine similarity inside Lambda, then live data is pulled and charted.", "Ships as an npm package with a cross-account CDK construct that provisions all permissions."],
      impact: "Any team can import it and query its metrics in plain language, without paying for a managed vector database.",
      links: [] },
    { id: "p-fraud", title: "FraudScope360", group: ["Agents & systems"],
      line: "Multimodal fraud detection. National winner, Citi Bank Campus Innovation Challenge.",
      chips: ["Graph ML", "XGBoost", "FastAPI"],
      problem: "Fraud rarely looks suspicious one account at a time. It shows up in the connections between accounts, identities and behaviour.",
      built: ["A 5-module engine combining graph embeddings, anomaly detection and XGBoost on engineered features.", "Coverage for fraud rings and identity fraud, served through FastAPI."],
      impact: "Combines several weak signals into one decision, closer to how real fraud teams work than a single classifier.",
      links: [] },
    { id: "p-fsense", title: "FraudSense AI", group: ["Agents & systems"],
      line: "Detecting LLM-assisted cheating in interviews.",
      chips: ["LLM detection", "Biometrics", "LLM judge"],
      problem: "Candidates can read answers generated by an LLM during a live interview.",
      built: ["Fuses DetectGPT-style text signals, biometric cues and an LLM judge into one score."],
      impact: "Gives interviewers a combined signal instead of a single brittle detector.",
      links: [] },
    { id: "p-dim", title: "Data in Motion", group: ["Agents & systems"],
      line: "Deciding where cloud data should live, then moving it.",
      chips: ["Optimisation", "Kafka", "Cloud"],
      problem: "Storage tiers and regions trade off cost against latency, and the right placement changes as access patterns change.",
      built: ["A mixed-integer program chooses placement; a Kafka pipeline carries out migrations."],
      impact: "Turns storage placement into an optimisation problem rather than a manual decision.",
      links: [] }
  ],

  jobs: [
    { co: "Nurix AI", initial: "N", role: "ML Engineering Intern", when: "Jul to Dec 2025", color: "#6ff0df",
      pts: ["Built and deployed a TinyBERT + NN voicemail detector with backend integration (95% precision).", "Improved real-time turn-end detection in a transformer speech-to-text pipeline using semantic parsing.", "Designed a word-error correction pipeline (Word2Vec, phonetic normalisation, LLM scoring) that cut WER by 40%."] },
    { co: "FidelFolio Investments", initial: "F", role: "Quant Investment Analyst", when: "May to Jun 2025", color: "#b9a6ff",
      pts: ["Built a research workflow for portfolio analytics and Sharpe evaluation, improving research efficiency by 90%.", "Used genetic algorithms and Bayesian optimisation for risk-aware portfolios, improving Sharpe by about 42%.", "Analysed 24 factors across 200+ portfolios."] },
    { co: "Grasim (Aditya Birla Group)", initial: "G", role: "Research Engineer", when: "May to Jul 2024", color: "#ffc977",
      pts: ["Designed 20+ PLC-based railway simulations for autonomous control and safety validation.", "Engineered IR and IoT sensor networks for track monitoring with 98% trespassing detection accuracy."] },
    { co: "Khageshvara Aviation", initial: "K", role: "Product Development Lead and ML Intern", when: "May to Oct 2023", color: "#8fd0ff",
      pts: ["Developed CNN aerial vision pipelines for real-time human detection on UAVs.", "Built financial models and pitch strategy that helped secure DST funding."] }
  ],

  skills: [
    ["LLMs and NLP", [["PyTorch", "All research projects"], ["Transformers", "RvC, Nurix speech pipeline"], ["LLM evaluation", "Retrieval vs Computation"], ["Probing and ablation", "Reading Without Looking"], ["LangChain", "Agent tooling"]]],
    ["Vision", [["OpenCV", "UAV vision"], ["OCR", "Indic OCR research"], ["CNNs", "Aerial detection"]]],
    ["RL and generative", [["Diffusion models", "Volatility surfaces"], ["PPO", "Hedging agent"], ["vLLM", "OmniMesh"]]],
    ["Systems", [["Python", "Everything"], ["FastAPI", "OmniMesh, FraudScope360"], ["Docker", "Deployments"], ["AWS", "CloudWatch agent"], ["GCP", "Cloud work"], ["SQL", "Data work"], ["TypeScript", "Web builds"]]],
    ["Quant and classical ML", [["XGBoost", "FraudScope360"], ["Graph ML", "FraudScope360"], ["Portfolio optimisation", "FidelFolio"], ["Volatility modelling", "NIFTY surfaces"], ["CVaR", "Hedging evaluation"]]]
  ],

  shelf: {
    book: {
      title: "My ML study module",
      status: "Open on Drive",
      blurb: "Notes, maths, papers and experiments I am writing up for myself — the study module lives on Google Drive.",
      link: "https://drive.google.com/drive/home",
      chapters: [
        "Probability and linear algebra refreshers",
        "Transformers from the ground up",
        "Evaluation and probing methods",
        "Diffusion and generative models",
        "RL for control and hedging"
      ]
    },
    sampleNote: "More library rows coming: LeetCode profile, watchlist videos, and reading notes. Swap sample items below when you have the real links.",
    rows: [
      { topic: "Transformers and LLMs", items: [
        { t: "Let's build GPT from scratch", by: "Andrej Karpathy", type: "Video", len: "1h 56m", url: "https://www.youtube.com/watch?v=kCc8FmEb1nY", why: "Best hands-on walkthrough of attention and training a tiny GPT." },
        { t: "Attention in transformers, visually explained", by: "3Blue1Brown", type: "Video", len: "26 min", url: "https://www.youtube.com/watch?v=eMlx5fFNoYc", why: "Clearest visual intuition for Q/K/V." },
        { t: "Attention Is All You Need", by: "Vaswani et al.", type: "Paper", len: "Paper", url: "https://arxiv.org/abs/1706.03762", why: "The original architecture paper." } ] },
      { topic: "Interpretability", items: [
        { t: "A Mathematical Framework for Transformer Circuits", by: "Elhage et al.", type: "Paper", len: "Paper", url: "https://transformer-circuits.pub/2021/framework/index.html", why: "Language for talking about circuits inside transformers." },
        { t: "Toy Models of Superposition", by: "Elhage et al.", type: "Paper", len: "Paper", url: "https://transformer-circuits.pub/2022/toy_model/index.html", why: "Why features pack into fewer dimensions." } ] },
      { topic: "Generative models and RL", items: [
        { t: "Denoising Diffusion Probabilistic Models", by: "Ho, Jain, Abbeel", type: "Paper", len: "Paper", url: "https://arxiv.org/abs/2006.11239", why: "Foundation for the volatility-surface work." },
        { t: "What are diffusion models?", by: "Lilian Weng", type: "Blog", len: "Blog", url: "https://lilianweng.github.io/posts/2021-07-11-diffusion-models/", why: "Clean survey before reading the DDPM paper." },
        { t: "Reinforcement Learning: An Introduction", by: "Sutton and Barto", type: "Book", len: "Book", url: "http://incompleteideas.net/book/the-book.html", why: "Reference for the hedging RL agent." } ] },
      { topic: "Practice and profiles (add yours)", items: [
        { t: "LeetCode — add profile link", by: "Adya", type: "Profile", len: "Soon", url: "#", why: "Paste your LeetCode URL here in content.js." } ] }
    ]
  },

  guardian: {
    intro: "Hi — I'm the guardian on Adya's site. Interview her through me: research, internships, projects, skills, or what she's looking for next. Answers come only from her documents.",
    chips: [
      ["Walk me through your research", "research"],
      ["What did you ship at Nurix?", "nurix"],
      ["Tell me about the OCR project", "ocr"],
      ["Why should we hire you?", "hire"],
      ["What are you looking for?", "looking"],
      ["How do you work on a team?", "team"]
    ],
    kb: [
      { id: "research", keys: ["research", "paper", "caisc", "reasoning", "retrieval", "computation", "fragility", "strategy", "llm", "llms", "probe", "probes", "interview"], src: "Paper abstract, project page",
        a: "My main research asks: when two LLMs get the same benchmark score, are they solving problems the same way? In Same Score, Different Strategy (CAISc 2026) I used three probes (entity rename, plan-versus-execution consistency, and closeness to training data) on 219 problems across arithmetic, planning and optimisation, with five models. Matched accuracy hid large differences: o3-mini went from a perfect score to zero on weighted interval scheduling after a rename. It is the first paper in a four-paper program on where retrieval and computation split inside models." },
      { id: "ocr", keys: ["ocr", "confidence", "indic", "vlm", "vision", "grounding", "calibration", "reading"], src: "Reading Without Looking project page",
        a: "Reading Without Looking tests whether OCR confidence reflects what the model sees. I trained a small OCR model from scratch so I could blank the image, add noise, scramble it and switch off the vision pathway. Confidence stayed around 0.9 while the correct first character had roughly 1e-11 probability, and a blank page got almost the same confidence as text. On held-out lines AUROC fell from 0.84 to about 0.57. The takeaway is that peak confidence is not a safe routing signal." },
      { id: "nurix", keys: ["nurix", "intern", "internship", "speech", "voicemail", "stt", "wer", "production", "shipped", "ship"], src: "Resume",
        a: "At Nurix AI (Jul to Dec 2025) I worked on production speech and NLP. I built and deployed a TinyBERT plus neural network voicemail detector with backend integration (95% precision), improved turn-end detection in a transformer speech-to-text pipeline using semantic parsing, and designed a word-error correction pipeline using Word2Vec, phonetic normalisation and LLM scoring that cut WER by 40%." },
      { id: "quant", keys: ["quant", "fidelfolio", "finance", "portfolio", "sharpe", "hedging", "ddpm", "diffusion", "volatility", "ppo", "nifty"], src: "Resume, project write-up",
        a: "On the finance side I did quant research at FidelFolio (portfolio optimisation with genetic algorithms and Bayesian optimisation, Sharpe up about 42%). I am also writing a paper that trains a diffusion model on 1,268 NIFTY 50 volatility surfaces to generate new market scenarios, then trains a PPO agent to hedge barrier options on them. It cut CVaR(95%) hedging error by 60.1% against Black-Scholes and is compared with a Heston-trained RL baseline." },
      { id: "agents", keys: ["agent", "agents", "agentic", "cloudwatch", "aws", "omnimesh", "mesh", "offline", "disaster", "gemma", "vllm", "equicontracts", "construction"], src: "Project write-ups",
        a: "On the systems side: OmniMesh is an offline disaster-response mesh where phones act as triage nodes, backed by a six-agent FastAPI service serving Gemma-2-9B with vLLM on an AMD GPU. CloudWatch in Plain English lets teams query AWS metrics in natural language using a Bedrock agent, embeddings in S3 and semantic search in Lambda." },
      { id: "fraud", keys: ["fraud", "fraudscope", "citi", "hackathon", "winner", "graph", "fraudsense"], src: "Resume",
        a: "FraudScope360 won the national round of the Citi Bank Campus Innovation Challenge. It is a five-module fraud engine combining graph machine learning, anomaly detection and XGBoost, covering fraud rings and identity fraud, served through FastAPI." },
      { id: "edu", keys: ["bits", "education", "college", "degree", "graduate", "university", "studied", "background"], src: "Resume",
        a: "I graduated from BITS Pilani in 2026 with a B.E. in Electrical and Electronics Engineering and a minor in Finance." },
      { id: "stack", keys: ["stack", "tools", "skills", "pytorch", "python", "languages", "framework", "frameworks", "strength"], src: "Resume",
        a: "Day to day: Python and PyTorch, with Transformers, scikit-learn and XGBoost. For systems work I use FastAPI, Docker, vLLM and AWS or GCP. I have also used OpenCV, LangChain, C++, SQL and TypeScript." },
      { id: "looking", keys: ["looking", "role", "roles", "hire", "hiring", "available", "job", "seeking", "want", "interested", "interests", "next", "open"], src: "Resume, profile",
        a: "I am looking for ML research and research engineering roles where I can build, run experiments and learn from people working on hard problems. My interests are LLM evaluation and reasoning, model internals and interpretability, and post-training and alignment." },
      { id: "hire", keys: ["hire", "why you", "strengths", "fit", "candidate", "offer", "value"], src: "Resume, papers",
        a: "I ship: a CAISc paper on LLM reasoning fragility, production speech work at Nurix that cut WER by 40%, and a national Citi Innovation win. I care about whether a metric actually means what people think it means — so I design probes and ablations, not only dashboards. I am comfortable moving between research and engineering." },
      { id: "team", keys: ["team", "collaborate", "collaboration", "work with", "communication", "mentor", "style"], src: "Experience write-ups",
        a: "I like clear write-ups and small demos that make a result checkable. At Nurix I worked inside a production speech stack with other engineers. I ask for the failure case early and prefer experiments you can re-run." },
      { id: "weak", keys: ["weakness", "weaknesses", "improve", "growth", "challenge", "hardest"], src: "Profile",
        a: "I can over-invest in getting the evaluation story right before shipping a rough prototype. I am getting better at landing a thin vertical slice first, then deepening the probes once something runs end to end." },
      { id: "study", keys: ["study", "book", "module", "learn", "learning", "shelf", "drive"], src: "Shelf",
        a: "I keep an ML study module on Google Drive — maths, papers and experiments in my own words. Open it from the Shelf stop, or ask me about a topic and I will point to the closest project or paper." },
      { id: "contact", keys: ["contact", "email", "reach", "resume", "cv", "github", "linkedin", "hello"], src: "Resume",
        a: "You can email srivastavadya@gmail.com, find code at github.com/Adya6714, or download the resume with the button at the top of the page." }
    ],
    fallback: "I don't have that in the documents I was given. You can email Adya at srivastavadya@gmail.com, or try one of the interview prompts above."
  }
};
