/* All site content lives here. Edit this file to change text, links, projects, notes and the shelf. */
window.CONTENT = {
  person: {
    name: "Adya Srivastava",
    line: "I research how language models solve problems, and build the ML systems around them.",
    proof: ["Paper at CAISc 2026", "Ex-ML Engineer, Nurix AI", "National winner, Citi Innovation Challenge"],
    status: "Open to ML research and research engineering roles",
    email: "srivastavadya@gmail.com",
    github: "https://github.com/Adya6714",
    linkedin: "https://www.linkedin.com/in/adyasri",
    openreview: "https://openreview.net/forum?id=d8w4gMVQ1w",
    aboutIntro: [
      "I'm Adya, an engineer who genuinely enjoys building things from scratch and figuring out how they work along the way. I'm especially interested in AI and ML, but what keeps me excited is the engineering and research around them: taking a vague question, digging into it, experimenting, breaking things, and eventually turning an idea into something that actually works. I love learning by building, and I'm constantly trying to go one level deeper than what I already know.",
      "I'm currently looking for opportunities where I can work closely on interesting problems in AI/ML, research, and engineering. I'm also here for the people side of it: if you're building something, thinking about a hackathon team, or found a resource that actually helped you learn, I want to hear about that too. Papers, repos, courses, events, or a half-formed idea are all fair game. Leave a slip below or say hi anytime."
    ],
    aboutCore: [
      "At the core, I like making things. I like starting with a blank page, learning whatever I need to learn, and slowly turning an idea into something real. Research gives me the opportunity to chase questions that don't have obvious answers, while engineering gives me the satisfaction of actually building the answer. AI and ML happen to sit at a particularly exciting intersection of the two for me.",
      "I don't think of learning as something that ends when you understand the theory. I want to understand enough to build with it, break it, question it, and hopefully discover something that wasn't obvious before. That's probably what keeps me moving between research papers, experiments, systems, and completely new things I know very little about. There's always something more to uncover, and that's the part I enjoy most."
    ]
  },

  suggest: {
    title: "Leave a slip",
    blurb: "Suggestions, leads, hackathon teammates, or resources worth knowing. Stay anonymous, or leave a way to reach you.",
    heroBlurb: "Ideas, collab, hackathon teams, or resources you swear by. I read every slip.",
    placeholder: "What should I explore, build, or read? Hackathon team-up? A course or repo that clicked for you?",
    prompts: [
      "Something I should explore",
      "Hackathon or build together",
      "A resource that actually helped",
      "A paper or idea to chase"
    ]
  },

  papers: [
    { title: "Same Score, Different Strategy", status: "CAISc 2026", kind: "published",
      note: "Multi-probe diagnosis of structural fragility in LLM reasoning.",
      links: [["Paper", "https://openreview.net/forum?id=d8w4gMVQ1w"], ["Project page", "https://adya6714.github.io/retrieval-vs-computation/"], ["Code", "https://github.com/Adya6714/retrieval-vs-computation"]] },
    { title: "Reading Without Looking", status: "Preprint", kind: "preprint",
      note: "Does OCR confidence track visual evidence? A controlled study on Indic scripts.",
      links: [["Project page", "https://adya6714.github.io/vlm-ocr-eval/"], ["PDF", "https://adya6714.github.io/vlm-ocr-eval/paper/main.pdf"], ["Code", "https://github.com/Adya6714/vlm-ocr-eval"]] },
    { title: "Diffusion volatility surfaces for RL hedging", status: "Preprint", kind: "preprint",
      note: "A model-risk decomposition of RL hedging trained on generated NIFTY surfaces.",
      links: [["Code", "https://github.com/Adya6714/ddpm-vol-hedging"], ["Paper", "https://github.com/Adya6714/ddpm-vol-hedging"]] },
    { title: "Hybrid quantum-classical paradigms", status: "Survey", kind: "survey",
      note: "Carleman linearization, variational PDEs, quantum RL, hardware comparisons.",
      links: [["PDF", "https://drive.google.com/file/d/1zwhnW2Nvl6I5myx556UoGED-1MKv9qt5/view?usp=sharing"]] },
    { title: "Retrieval vs Computation, papers 2–4", status: "Planned", kind: "planned",
      note: "Where the split lives in the network, what training produces it, and how it scales.",
      links: [] }
  ],

  notes: [
    { id: "n-rename", title: "A rename erased a perfect score", headline: "o3-mini: 1.00 to 0.00 after a rename", project: "Retrieval vs Computation",
      q: "Does a model that solves a problem perfectly still solve it when only the names change?",
      found: "On weighted interval scheduling, o3-mini scored a perfect 1.00 on the original problems and 0.00 after the entities were renamed. Every model that solved this subtype at all collapsed under the rename. Exposure and difficulty move together on this subtype, so this result alone cannot say which one is responsible.",
      why: "A benchmark would have reported this model as fully capable on the task. The rename shows the capability did not survive a change that leaves the problem identical.",
      link: ["Read the paper", "https://openreview.net/forum?id=d8w4gMVQ1w"] },
    { id: "n-spread", title: "One rename, very different effects", headline: "Same change, opposite directions across models", project: "Retrieval vs Computation",
      q: "If models simply recall memorised problems, shouldn't a rename hurt them all in the same way?",
      found: "The same rename helped three models substantially, left two at the floor, and even reversed direction across problem subtypes. On arithmetic, Gemini stayed steady when the numbers were regenerated (0.909 to 0.958) but fell to 0.523 when only the names changed.",
      why: "That spread is hard to explain with one shared retrieval mechanism. It points to model-specific strategies hiding under similar scores.",
      link: ["Project page", "https://adya6714.github.io/retrieval-vs-computation/"] },
    { id: "n-inject", title: "Accepting a wrong step is not derailing", headline: "88 to 100% accept an injected error, yet still finish", project: "Retrieval vs Computation",
      q: "If a model accepts a wrong intermediate value, does its answer go wrong too?",
      found: "When I injected an incorrect state mid-solve, compliant models accepted it 88 to 100% of the time. Accuracy after injection stayed close to uninterrupted performance (Claude 52.5%, GPT-4o 50.8%, o3-mini 37.7%), and whether a model complied did not predict whether it finished correctly.",
      why: "Following an injected value is not evidence that a model reasons from its own steps. Compliance and derailment have to be measured separately.",
      link: ["Read the paper", "https://openreview.net/forum?id=d8w4gMVQ1w"] },
    { id: "n-ambig", title: "Most instances stay ambiguous", headline: "61.6% of instances resist a clean label", project: "Retrieval vs Computation",
      q: "Can three behavioural probes label each problem as retrieved or computed?",
      found: "Combining the probes into a per-instance label sounds like the goal. Under strict thresholds, 61.6% of instances stayed ambiguous, so the labels work as calibration points rather than a verdict.",
      why: "It sets an honest bar for the next papers: per-instance diagnosis needs instruments validated beyond behaviour, which is where the mechanism work starts.",
      link: ["Read the paper", "https://openreview.net/forum?id=d8w4gMVQ1w"] },
    { id: "n-harness", title: "My harness caught my own bugs", headline: "Gold in, gold out, before any result", project: "Retrieval vs Computation",
      q: "How do you know a probe measures the model and not your own verifier?",
      found: "Every probe was checked gold in, gold out: feed the verifier known-correct answers and confirm they score as correct. Those checks caught several verifier bugs in my own pipeline before they reached the results.",
      why: "Behavioural probes are fragile instruments. Checking the instrument is part of the experiment, not cleanup.",
      link: ["Code and audit", "https://github.com/Adya6714/retrieval-vs-computation"] },
    { id: "n-pos0", title: "90% confident, almost never right", headline: "Confidence 0.90, correct answer ~10⁻¹¹", project: "Reading Without Looking",
      q: "When an OCR model says it is 90% sure, is that about the image?",
      found: "At the first character, where no earlier text can help, my OCR model reported about 0.90 confidence while the correct character had roughly 2×10⁻¹¹ probability. It was the top choice 0 times in 180 evaluations.",
      why: "Confidence measured how peaked the output was, not whether the image supported the answer.",
      link: ["Project page", "https://adya6714.github.io/vlm-ocr-eval/"] },
    { id: "n-blank", title: "A blank page gets the same confidence", headline: "Text 0.994, blank page 0.990", project: "Reading Without Looking",
      q: "If confidence depends on vision, removing the image should lower it. Does it?",
      found: "Blank, noise and scrambled images barely moved confidence (0.994 for text against 0.990 for a blank page). Switching off the vision pathway changed about 8% of predictions while confidence stayed almost flat.",
      why: "A routing system that trusts confidence would wave exactly these pages through.",
      link: ["Project page", "https://adya6714.github.io/vlm-ocr-eval/"] },
    { id: "n-auroc", title: "Good AUROC can still mislead", headline: "AUROC 0.84 in-sample, 0.57 held out", project: "Reading Without Looking",
      q: "Is confidence useful for separating right from wrong answers?",
      found: "On familiar lines, confidence separated right from wrong reasonably well (AUROC 0.838). On held-out lines it dropped to about 0.57, with a calibration error of 0.811.",
      why: "A meter that looks good in-sample can be close to useless for decisions on new pages. Held-out checks have to come before any routing claim.",
      link: ["Project page", "https://adya6714.github.io/vlm-ocr-eval/"] }
  ],

  projects: [
    { id: "p-rvc", title: "Retrieval vs Computation", group: ["Research"], demo: "rvc",
      line: "A measurement toolkit for telling whether an LLM reasoned or recalled.",
      chips: ["LLM evaluation", "Reasoning", "Robustness"],
      problem: "Benchmarks say whether an answer is right, not how the model got there. Two models with the same score can fail in very different ways once deployed.",
      built: ["Three probes: rewording and renaming, plan-versus-execution consistency, and closeness to training data.", "219 problems across arithmetic, planning and optimisation, run on five models (about 20,000 API calls), with exact checkers for every answer.", "A reproducible pipeline: raw runs, derived metrics, paper tables and tests all regenerate from code."],
      impact: "Gives teams a way to judge which models to trust on unseen problems, not just which score highest. Phase one of a four-paper program on where retrieval and computation split inside LLMs.",
      links: [["Site", "https://adya6714.github.io/retrieval-vs-computation/"], ["Code", "https://github.com/Adya6714/retrieval-vs-computation"], ["Paper", "https://openreview.net/forum?id=d8w4gMVQ1w"]] },
    { id: "p-ocr", title: "Reading Without Looking", group: ["Research"], demo: "ocr",
      line: "Can you trust OCR confidence on Indic scripts?",
      chips: ["Vision-language", "Calibration", "Indic OCR"],
      problem: "Document systems auto-accept pages with high confidence and send the rest to people. That only works if confidence tracks what the model actually sees, and Indic scripts make this hard to measure.",
      built: ["Grapheme-level scoring and a HarfBuzz renderer that produces real Indic script shaping.", "A 19.6M-parameter OCR model trained from scratch, so every internal step can be inspected.", "Counterfactual probes an API cannot run (blank, noise and scrambled images, removing the vision pathway), plus a transfer test on a production OCR API with pre-registered statistics."],
      impact: "Shows peak confidence can stay high while the image contributes almost nothing, so routing on it alone can fail. Proposes grounding-aware confidence instead.",
      links: [["Site", "https://adya6714.github.io/vlm-ocr-eval/"], ["Code", "https://github.com/Adya6714/vlm-ocr-eval"], ["Preprint", "https://adya6714.github.io/vlm-ocr-eval/paper/main.pdf"]] },
    { id: "p-ddpm", title: "Synthetic Volatility Surfaces for Hedging", group: ["Research", "Quant"], demo: "ddpm",
      line: "Diffusion-generated NIFTY 50 volatility surfaces to train an RL hedging agent.",
      chips: ["Diffusion models", "Reinforcement learning", "Quant"],
      problem: "Training a hedging agent needs far more market scenarios than history provides, and an agent trained on one model of the market inherits that model's blind spots.",
      built: ["A dataset of 1,268 NIFTY implied volatility surfaces (2018 to 2026) built from 912K+ NSE option rows.", "A conditional diffusion model that generates new surfaces with fewer arbitrage violations than market data (penalty 0.005 vs 0.009).", "A PPO hedging agent for barrier options, compared against a Heston-trained RL baseline."],
      impact: "Cut tail-risk hedging error (CVaR 95%) by 60.1% against Black-Scholes, and separates how much of the result comes from the generator versus the agent.",
      links: [["Code", "https://github.com/Adya6714/ddpm-vol-hedging"], ["Paper", "https://github.com/Adya6714/ddpm-vol-hedging"]] },
    { id: "p-mesh", title: "OmniMesh", group: ["Agents & systems"],
      line: "An offline disaster-response network with an AI triage backend.",
      chips: ["Multi-agent", "LLM serving", "Edge"],
      problem: "In disasters, internet and cell networks fail first, exactly when responders need to coordinate and triage.",
      built: ["Android phones act as triage nodes in an offline-first, peer-to-peer mesh.", "A six-agent FastAPI backend serving Gemma-2-9B with vLLM on an AMD GPU.", "Sync to the cloud once connectivity returns."],
      impact: "Keeps communication and decision support working when infrastructure is down. Built for the AMD Developer Hackathon ACT II and entered in the Google Solution Challenge 2025.",
      links: [["Code", "https://github.com/Adya6714/OmniMesh"]] },
    { id: "p-equi", title: "EquiContracts", group: ["Agents & systems"],
      line: "Turns construction-project email into structured, verified contract data.",
      chips: ["Agents", "FastAPI", "Construction"],
      problem: "Routine contractor email is the source of truth for bank guarantees, milestones and payments — but it stays unstructured.",
      built: ["Agentic extraction and deterministic YAML rules for Indian contracting workflows.", "Contractor write path with client/PMC verified dashboards.", "Postgres with row-level security and an isolated AI extraction package."],
      impact: "Shared evidence locker for contractor and client without trusting free-text email alone.",
      links: [["Code", "https://github.com/Adya6714/EquiContracts"]] },
    { id: "p-fraud", title: "FraudScope360", group: ["Agents & systems"],
      line: "Multimodal fraud detection. National winner, Citi Bank Campus Innovation Challenge.",
      chips: ["Graph ML", "XGBoost", "FastAPI"],
      problem: "Fraud rarely looks suspicious one account at a time. It shows up in the connections between accounts, identities and behaviour.",
      built: ["A 5-module engine combining graph embeddings, anomaly detection and XGBoost on engineered features.", "Coverage for fraud rings and identity fraud, served through FastAPI."],
      impact: "Combines several weak signals into one decision, closer to how real fraud teams work than a single classifier.",
      links: [["Code", "https://github.com/Adya6714/FraudScope360"]] },
    { id: "p-fsense", title: "FraudSense AI", group: ["Agents & systems"],
      line: "Detecting LLM-assisted cheating in interviews.",
      chips: ["LLM detection", "Biometrics", "LLM judge"],
      problem: "Candidates can read answers generated by an LLM during a live interview.",
      built: ["Fuses DetectGPT-style text signals, biometric cues and an LLM judge into one score."],
      impact: "Gives interviewers a combined signal instead of a single brittle detector.",
      links: [["Code", "https://github.com/Adya6714/FraudSense-AI"]] },
    { id: "p-dim", title: "Data in Motion", group: ["Agents & systems"],
      line: "Deciding where cloud data should live, then moving it.",
      chips: ["Optimisation", "Kafka", "Cloud"],
      problem: "Storage tiers and regions trade off cost against latency, and the right placement changes as access patterns change.",
      built: ["A mixed-integer program chooses placement; a Kafka pipeline carries out migrations."],
      impact: "Turns storage placement into an optimisation problem rather than a manual decision.",
      links: [["Code", "https://github.com/Adya6714/data-in-motion"]] },
    { id: "p-ganga", title: "Ganga MRV", group: ["Research", "Quant"],
      line: "MRV pipeline for enhanced rock weathering carbon removal, with a live dashboard.",
      chips: ["Climate", "Statistics", "Python"],
      problem: "Carbon-removal credits need measurement that survives counterfactuals, not just a single before/after delta.",
      built: ["Full MRV pipeline on a synthetic 12-sample Project Ganga dataset.", "Five independent methods that agree the credit claim fails.", "Teaching book plus a live dashboard walkthrough."],
      impact: "Shows how to reject a credit with transparent, reproducible checks.",
      links: [["Site", "https://site-eight-khaki-34.vercel.app"], ["Code", "https://github.com/Adya6714/ganga-mrv"]] },
    { id: "p-traffic", title: "GridLock 2.0", group: ["Research"],
      line: "Spatiotemporal traffic demand prediction per geohash and 15-minute slot.",
      chips: ["Forecasting", "Competition", "Python"],
      problem: "Normalized traffic demand varies sharply across space and time; a model has to respect both.",
      built: ["Competition pipeline for geohash × slot demand forecasting.", "Documented research journey and reproducible notebook.", "Leaderboard score 87.90 with no external data."],
      impact: "A clean baseline for short-horizon traffic demand under competition constraints.",
      links: [["Code", "https://github.com/Adya6714/traffic-prediction"]] },
    { id: "p-social", title: "ContentPulse", group: ["Agents & systems"],
      line: "Social post analyzer that returns structured engagement insights with Gemini.",
      chips: ["LLM", "OCR", "Full-stack"],
      problem: "Creators need concrete feedback on posts, not a single vanity score.",
      built: ["PDF, image (OCR) and raw text intake.", "Gemini-backed structured JSON feedback for the frontend.", "Deployed frontend on Vercel and API on Railway."],
      impact: "A production path from messy post content to readable engagement advice.",
      links: [["Site", "https://social-analyzer-six.vercel.app"], ["Code", "https://github.com/Adya6714/social-analyzer"]] },
    { id: "p-price", title: "Smart Pricing 360", group: ["Research", "Quant"],
      line: "Multimodal product price prediction for a 2025 hackathon.",
      chips: ["Multimodal", "Pricing", "ML"],
      problem: "Product price depends on both text and image cues that single-modality models miss.",
      built: ["Multimodal architecture for catalog pricing.", "Hackathon submission with documented setup and GCP optional path."],
      impact: "End-to-end pricing model that uses listing text and imagery together.",
      links: [["Code", "https://github.com/Adya6714/smart-pricing360"]] },
    { id: "p-routecast", title: "RouteCast360", group: ["Research", "Quant"],
      line: "Forecast final seat counts for intercity routes from booking signals.",
      chips: ["CatBoost", "Forecasting", "Travel"],
      problem: "Operators need final seat counts before departure, from noisy search and booking streams.",
      built: ["CatBoost regression with target encodings and calendar features.", "GroupKFold evaluation by day-of-year.", "Submission pipeline from transactional CSVs."],
      impact: "Turns booking/search history into a route-level demand forecast.",
      links: [["Code", "https://github.com/Adya6714/RouteCast360"]] },
    { id: "p-pdf", title: "PDF Extractor", group: ["Agents & systems"],
      line: "Outline extraction and persona-based document intelligence for PDFs.",
      chips: ["NLP", "Embeddings", "Documents"],
      problem: "Long PDFs bury the sections a given reader actually needs.",
      built: ["Hierarchical outline extractor (1A).", "Persona-based semantic selection with embeddings (1B).", "Dockerised batch processing."],
      impact: "Structured outlines plus reader-aware highlights from the same PDF stack.",
      links: [["Code", "https://github.com/Adya6714/pdf_extractor"]] },
    { id: "p-meme", title: "Meme Coin Aggregator", group: ["Agents & systems"],
      line: "Real-time meme-coin data API across DEX sources.",
      chips: ["TypeScript", "WebSocket", "DeFi"],
      problem: "Token data is scattered across DexScreener, GeckoTerminal and similar feeds.",
      built: ["Unified API with caching, deduplication, sorting and pagination.", "WebSocket updates for live token streams."],
      impact: "One backend surface for meme-coin market data.",
      links: [["Code", "https://github.com/Adya6714/meme-coin-aggregator"]] },
    { id: "p-wml", title: "WML — Who's Most Like…?", group: ["Agents & systems"],
      line: "A lightweight party game: draw a word, tag the friend who matches.",
      chips: ["React", "Flask", "Game"],
      problem: "Need a fast social icebreaker that still has a live leaderboard.",
      built: ["Word pool with skip/return.", "Friend profiles and auto-updating leaderboard.", "React frontend with Flask API."],
      impact: "A deployed playful game for small groups.",
      links: [["Site", "https://wml-ten.vercel.app"], ["Code", "https://github.com/Adya6714/WML"]] },
    { id: "p-tasks", title: "Task Board", group: ["Agents & systems"],
      line: "Kanban-style task board web app.",
      chips: ["JavaScript", "Frontend"],
      problem: "Simple personal task tracking without a heavy SaaS board.",
      built: ["Browser task board UI.", "Deployed on Vercel."],
      impact: "A lightweight board for day-to-day tasks.",
      links: [["Site", "https://task-board-app-bay.vercel.app"], ["Code", "https://github.com/Adya6714/task-board-app"]] },
    { id: "p-ondc", title: "ONDC Food Platform", group: ["Agents & systems"],
      line: "Backend linking farmers, restaurants and food banks on ONDC-style flows.",
      chips: ["Python", "Supply chain"],
      problem: "Surplus food and demand sit in different systems with little shared inventory logic.",
      built: ["User types for farmer, restaurant and food bank.", "Inventory management and simple demand prediction."],
      impact: "A starter backend for food redistribution on an ONDC-like network.",
      links: [["Code", "https://github.com/Adya6714/ONDC-Food-Platform"]] },
    { id: "p-psms", title: "PSMS", group: ["Agents & systems"],
      line: "Project and service management system (web).",
      chips: ["JavaScript", "Web"],
      problem: "Small teams need a lightweight place to track projects and services.",
      built: ["JavaScript web app structure for project/service tracking."],
      impact: "A starting point for internal project ops UI.",
      links: [["Code", "https://github.com/Adya6714/PSMS"]] },
    { id: "p-atari", title: "Atari RL Agent", group: ["Research"],
      line: "Deep Q-learning agent for classic Atari from early RL study notes.",
      chips: ["RL", "DQN", "Atari"],
      problem: "Learn deep Q-learning end to end on a visual game environment.",
      built: ["CNN-based DQN pipeline on Atari frames.", "Study notes tied to Silver lectures and FreeCodeCamp RL."],
      impact: "Hands-on DQN baseline from the start of the RL path.",
      links: [["Code", "https://github.com/Adya6714/Atari-game-RL-Agent"]] },
    { id: "p-cw", title: "CloudWatch in Plain English", group: ["Agents & systems"],
      line: "Ask AWS metrics questions in natural language and get charts back.",
      chips: ["Agents", "Semantic search", "AWS", "Private"],
      problem: "Finding the right CloudWatch metric means knowing its exact name and digging through the console or CLI.",
      built: ["A Bedrock agent describes every metric; descriptions become embeddings stored in S3 with metadata in DynamoDB, refreshed weekly.", "Queries are embedded and matched by cosine similarity inside Lambda, then live data is pulled and charted.", "Ships as an npm package with a cross-account CDK construct that provisions all permissions."],
      impact: "Any team can import it and query its metrics in plain language, without paying for a managed vector database.",
      links: [] }
  ],

  jobs: [
    { co: "Nurix AI", initial: "N", role: "ML Engineering Intern", when: "Jul to Dec 2025", color: "#6ff0df",
      pts: ["Built and deployed a TinyBERT + NN voicemail detector with backend integration (95% precision).", "Improved real-time turn-end detection in a transformer speech-to-text pipeline using semantic parsing.", "Designed a word-error correction pipeline (Word2Vec, phonetic normalisation, LLM scoring) that cut WER by 40%."] },
    { co: "FidelFolio Investments", initial: "F", role: "Quant Investment Analyst", when: "May to Jun 2025", color: "#b9a6ff",
      pts: ["Built a research workflow for portfolio analytics and Sharpe evaluation, improving research efficiency by 90%.", "Used genetic algorithms and Bayesian optimisation for risk-aware portfolios, improving Sharpe by about 42%.", "Analysed 24 factors across 200+ portfolios."] },
    { co: "Grasim (Aditya Birla Group)", initial: "G", role: "Research Engineer", when: "May to Jul 2024", color: "#ffc977",
      pts: ["Designed 20+ PLC-based railway simulations for autonomous control and safety validation.", "Engineered IR and IoT sensor networks for track monitoring with 98% trespassing detection accuracy."] },
    { co: "Khageshvara Aviation", initial: "K", role: "Product Development Lead and ML Intern", when: "May to Oct 2023", color: "#8fd0ff",
      pts: ["Developed CNN aerial vision pipelines for real-time human detection on UAVs.", "Built financial models and pitch strategy that helped secure DST funding."] }
  ],

  skills: [
    ["LLMs and NLP", [["PyTorch", "All research projects"], ["Transformers", "RvC, Nurix speech pipeline"], ["LLM evaluation", "Retrieval vs Computation"], ["Probing and ablation", "Reading Without Looking"], ["LangChain", "Agent tooling"]]],
    ["Vision", [["OpenCV", "UAV vision"], ["OCR", "Indic OCR research"], ["CNNs", "Aerial detection"]]],
    ["RL and generative", [["Diffusion models", "Volatility surfaces"], ["PPO", "Hedging agent"], ["vLLM", "OmniMesh"]]],
    ["Systems", [["Python", "Everything"], ["FastAPI", "OmniMesh, FraudScope360"], ["Docker", "Deployments"], ["AWS", "CloudWatch agent"], ["GCP", "Cloud work"], ["SQL", "Data work"], ["TypeScript", "Web builds"]]],
    ["Quant and classical ML", [["XGBoost", "FraudScope360"], ["Graph ML", "FraudScope360"], ["Portfolio optimisation", "FidelFolio"], ["Volatility modelling", "NIFTY surfaces"], ["CVaR", "Hedging evaluation"]]]
  ],

  shelf: {
    book: {
      title: "My ML study module",
      status: "Open on Drive",
      blurb: "Notes, maths, papers and experiments I am writing up for myself — the study module lives on Google Drive.",
      link: "https://drive.google.com/drive/home",
      chapters: [
        "Probability and linear algebra refreshers",
        "Transformers from the ground up",
        "Evaluation and probing methods",
        "Diffusion and generative models",
        "RL for control and hedging"
      ]
    },
    meraki: {
      title: "MERAKI",
      tagline: "An Alleyway to Sonder",
      home: "https://srivastavadya.wixsite.com/meraki14",
      blog: "https://srivastavadya.wixsite.com/meraki14/blog",
      about: "Meraki is where I share poems, experiences and perceptions — small worlds built in words. Outside engineering I write about people, nature and the quieter parts of ambition.",
      posts: [
        { t: "Justice of Time", date: "Nov 16, 2023", min: "2 min", url: "https://srivastavadya.wixsite.com/meraki14/post/justice-of-time", blurb: "But, there will be a time… when the sun would bleed in red…" },
        { t: "Laughingly", date: "Nov 15, 2023", min: "1 min", url: "https://srivastavadya.wixsite.com/meraki14/post/laughingly", blurb: "Amidst the cluster, I stood in — a smile had my face covered…" },
        { t: "Birth of an Evil", date: "Nov 15, 2023", min: "3 min", url: "https://srivastavadya.wixsite.com/meraki14/post/birth-of-an-evil", blurb: "As the clouds of the night swept the sky…" },
        { t: "Hallucinate the Ricochet", date: "Nov 15, 2023", min: "6 min", url: "https://srivastavadya.wixsite.com/meraki14/post/hallucinate-the-ricochet", blurb: "A poem as story — too proud to believe life flashes before death." },
        { t: "Stupidity", date: "Nov 15, 2023", min: "1 min", url: "https://srivastavadya.wixsite.com/meraki14/post/stupidity", blurb: "Two sides of selfishness — an unnecessary evil." },
        { t: "Two", date: "Nov 15, 2023", min: "1 min", url: "https://srivastavadya.wixsite.com/meraki14/post/__two", blurb: "Two are the coconuts knocking… two are the stars twinkling…" },
        { t: "The Right Path", date: "Nov 15, 2023", min: "1 min", url: "https://srivastavadya.wixsite.com/meraki14/post/the-right-path", blurb: "As I was walking through the lane, darkness stayed with me…" },
        { t: "Soon…", date: "Jul 25, 2023", min: "2 min", url: "https://srivastavadya.wixsite.com/meraki14/post/_soon", blurb: "And I know for a fact we'd be sitting on the stairs…" },
        { t: "Heaven", date: "Apr 20, 2023", min: "2 min", url: "https://srivastavadya.wixsite.com/meraki14/post/heaven", blurb: "There is no ultimate that ever existed…" },
        { t: "SHIELDED…", date: "Mar 13, 2023", min: "2 min", url: "https://srivastavadya.wixsite.com/meraki14/post/shielded", blurb: "To be young is a boon — for the euphoria sparked inside…" },
        { t: "Lustre", date: "Mar 8, 2023", min: "1 min", url: "https://srivastavadya.wixsite.com/meraki14/post/lustre", blurb: "As she sat on her balcony…" },
        { t: "The Little Boy", date: "Mar 8, 2023", min: "1 min", url: "https://srivastavadya.wixsite.com/meraki14/post/the-little-boy", blurb: "With the children playing in the park…" },
        { t: "Twinkling", date: "Mar 7, 2023", min: "1 min", url: "https://srivastavadya.wixsite.com/meraki14/post/twinkling", blurb: "Goodness is not kindness…" }
      ]
    },
    sampleNote: "Study notes and resources I learn from. Horizontal rows scroll inside the panel.",
    rows: [
      { topic: "Transformers and LLMs", items: [
        { t: "Let's build GPT from scratch", by: "Andrej Karpathy", type: "Video", len: "1h 56m", url: "https://www.youtube.com/watch?v=kCc8FmEb1nY", why: "Best hands-on walkthrough of attention and training a tiny GPT." },
        { t: "Attention in transformers, visually explained", by: "3Blue1Brown", type: "Video", len: "26 min", url: "https://www.youtube.com/watch?v=eMlx5fFNoYc", why: "Clearest visual intuition for Q/K/V." },
        { t: "Attention Is All You Need", by: "Vaswani et al.", type: "Paper", len: "Paper", url: "https://arxiv.org/abs/1706.03762", why: "The original architecture paper." } ] },
      { topic: "Interpretability", items: [
        { t: "A Mathematical Framework for Transformer Circuits", by: "Elhage et al.", type: "Paper", len: "Paper", url: "https://transformer-circuits.pub/2021/framework/index.html", why: "Language for talking about circuits inside transformers." },
        { t: "Toy Models of Superposition", by: "Elhage et al.", type: "Paper", len: "Paper", url: "https://transformer-circuits.pub/2022/toy_model/index.html", why: "Why features pack into fewer dimensions." } ] },
      { topic: "Generative models and RL", items: [
        { t: "Denoising Diffusion Probabilistic Models", by: "Ho, Jain, Abbeel", type: "Paper", len: "Paper", url: "https://arxiv.org/abs/2006.11239", why: "Foundation for the volatility-surface work." },
        { t: "What are diffusion models?", by: "Lilian Weng", type: "Blog", len: "Blog", url: "https://lilianweng.github.io/posts/2021-07-11-diffusion-models/", why: "Clean survey before reading the DDPM paper." },
        { t: "Reinforcement Learning: An Introduction", by: "Sutton and Barto", type: "Book", len: "Book", url: "http://incompleteideas.net/book/the-book.html", why: "Reference for the hedging RL agent." } ] },
      { topic: "Practice and profiles", items: [
        { t: "LeetCode — add profile link", by: "Adya", type: "Profile", len: "Soon", url: "#", why: "Paste your LeetCode URL here in content.js when ready." } ] }
    ]
  },

  more: {
    title: "More",
    blurb: "Personal writing and older product or coursework write-ups. Not the main ML thread on the river.",
    offProjects: [
      { t: "Citizen Services App", type: "PDF", url: "assets/case-studies/citizen-services-app.pdf", why: "Civic services product write-up." },
      { t: "Cloud Computing in Healthcare", type: "PDF", url: "assets/case-studies/cloud-computing-healthcare.pdf", why: "Cloud patterns in clinical workflows." },
      { t: "Zepto assignment", type: "PDF", url: "assets/case-studies/zepto-assignment.pdf", why: "Quick-commerce operations case." },
      { t: "Consulting case", type: "PDF", url: "assets/case-studies/consulting-case.pdf", why: "Structured consulting analysis." },
      { t: "Business case study", type: "PDF", url: "assets/case-studies/business-case-study.pdf", why: "Case framing and recommendation." },
      { t: "Idea guidebook", type: "PDF", url: "assets/case-studies/idea-guidebook.pdf", why: "Scoping a rough idea into a product." },
      { t: "Pitch deck", type: "PDF", url: "assets/case-studies/pitch-deck.pdf", why: "Startup-style pitch narrative." },
      { t: "TAS write-up", type: "PDF", url: "assets/case-studies/tas.pdf", why: "Systems analysis notes." },
      { t: "MT assignment", type: "PDF", url: "assets/case-studies/mt-assignment.pdf", why: "Course technical write-up." }
    ]
  },

  guardian: {
    intro: "If none of the threads above cover what you wanted to know, ask here. Research, projects, experience, what I'm looking for next. I'll answer as best I can.",
    chips: [
      ["Walk me through your research", "research"],
      ["What did you ship at Nurix?", "nurix"],
      ["Tell me about the OCR project", "ocr"],
      ["Why should we hire you?", "hire"],
      ["What are you looking for?", "looking"],
      ["How do you work on a team?", "team"]
    ],
    kb: [
      { id: "research", keys: ["research", "paper", "caisc", "reasoning", "retrieval", "computation", "fragility", "strategy", "llm", "llms", "probe", "probes", "interview"], src: "Paper abstract, project page",
        a: "My main research asks: when two LLMs get the same benchmark score, are they solving problems the same way? In Same Score, Different Strategy (CAISc 2026) I used three probes (entity rename, plan-versus-execution consistency, and closeness to training data) on 219 problems across arithmetic, planning and optimisation, with five models. Matched accuracy hid large differences: o3-mini went from a perfect score to zero on weighted interval scheduling after a rename. It is the first paper in a four-paper program on where retrieval and computation split inside models." },
      { id: "ocr", keys: ["ocr", "confidence", "indic", "vlm", "vision", "grounding", "calibration", "reading"], src: "Reading Without Looking project page",
        a: "Reading Without Looking tests whether OCR confidence reflects what the model sees. I trained a small OCR model from scratch so I could blank the image, add noise, scramble it and switch off the vision pathway. Confidence stayed around 0.9 while the correct first character had roughly 1e-11 probability, and a blank page got almost the same confidence as text. On held-out lines AUROC fell from 0.84 to about 0.57. The takeaway is that peak confidence is not a safe routing signal." },
      { id: "nurix", keys: ["nurix", "intern", "internship", "speech", "voicemail", "stt", "wer", "production", "shipped", "ship"], src: "Resume",
        a: "At Nurix AI (Jul to Dec 2025) I worked on production speech and NLP. I built and deployed a TinyBERT plus neural network voicemail detector with backend integration (95% precision), improved turn-end detection in a transformer speech-to-text pipeline using semantic parsing, and designed a word-error correction pipeline using Word2Vec, phonetic normalisation and LLM scoring that cut WER by 40%." },
      { id: "quant", keys: ["quant", "fidelfolio", "finance", "portfolio", "sharpe", "hedging", "ddpm", "diffusion", "volatility", "ppo", "nifty"], src: "Resume, project write-up",
        a: "On the finance side I did quant research at FidelFolio (portfolio optimisation with genetic algorithms and Bayesian optimisation, Sharpe up about 42%). I am also writing a paper that trains a diffusion model on 1,268 NIFTY 50 volatility surfaces to generate new market scenarios, then trains a PPO agent to hedge barrier options on them. It cut CVaR(95%) hedging error by 60.1% against Black-Scholes and is compared with a Heston-trained RL baseline." },
      { id: "agents", keys: ["agent", "agents", "agentic", "cloudwatch", "aws", "omnimesh", "mesh", "offline", "disaster", "gemma", "vllm", "equicontracts", "construction"], src: "Project write-ups",
        a: "On the systems side: OmniMesh is an offline disaster-response mesh where phones act as triage nodes, backed by a six-agent FastAPI service serving Gemma-2-9B with vLLM on an AMD GPU. CloudWatch in Plain English lets teams query AWS metrics in natural language using a Bedrock agent, embeddings in S3 and semantic search in Lambda." },
      { id: "fraud", keys: ["fraud", "fraudscope", "citi", "hackathon", "winner", "graph", "fraudsense"], src: "Resume",
        a: "FraudScope360 won the national round of the Citi Bank Campus Innovation Challenge. It is a five-module fraud engine combining graph machine learning, anomaly detection and XGBoost, covering fraud rings and identity fraud, served through FastAPI." },
      { id: "edu", keys: ["bits", "education", "college", "degree", "graduate", "university", "studied", "background"], src: "Resume",
        a: "I graduated from BITS Pilani in 2026 with a B.E. in Electrical and Electronics Engineering and a minor in Finance." },
      { id: "stack", keys: ["stack", "tools", "skills", "pytorch", "python", "languages", "framework", "frameworks", "strength"], src: "Resume",
        a: "Day to day: Python and PyTorch, with Transformers, scikit-learn and XGBoost. For systems work I use FastAPI, Docker, vLLM and AWS or GCP. I have also used OpenCV, LangChain, C++, SQL and TypeScript." },
      { id: "looking", keys: ["looking", "role", "roles", "hire", "hiring", "available", "job", "seeking", "want", "interested", "interests", "next", "open"], src: "Resume, profile",
        a: "I am looking for ML research and research engineering roles where I can build, run experiments and learn from people working on hard problems. My interests are LLM evaluation and reasoning, model internals and interpretability, and post-training and alignment." },
      { id: "hire", keys: ["hire", "why you", "strengths", "fit", "candidate", "offer", "value"], src: "Resume, papers",
        a: "I ship: a CAISc paper on LLM reasoning fragility, production speech work at Nurix that cut WER by 40%, and a national Citi Innovation win. I care about whether a metric actually means what people think it means — so I design probes and ablations, not only dashboards. I am comfortable moving between research and engineering." },
      { id: "team", keys: ["team", "collaborate", "collaboration", "work with", "communication", "mentor", "style"], src: "Experience write-ups",
        a: "I like clear write-ups and small demos that make a result checkable. At Nurix I worked inside a production speech stack with other engineers. I ask for the failure case early and prefer experiments you can re-run." },
      { id: "weak", keys: ["weakness", "weaknesses", "improve", "growth", "challenge", "hardest"], src: "Profile",
        a: "I can over-invest in getting the evaluation story right before shipping a rough prototype. I am getting better at landing a thin vertical slice first, then deepening the probes once something runs end to end." },
      { id: "study", keys: ["study", "book", "module", "learn", "learning", "shelf", "drive", "blog", "blogs", "case study", "case studies", "writing", "meraki", "poem", "poems", "poetry"], src: "Shelf",
        a: "On the Shelf stop you will find Meraki — my poetry journal (An Alleyway to Sonder) with posts like Justice of Time and Hallucinate the Ricochet, plus an ML study module on Drive and technical case-study PDFs. Open Meraki from the Shelf, or the full site at srivastavadya.wixsite.com/meraki14." },
      { id: "contact", keys: ["contact", "email", "reach", "resume", "cv", "github", "linkedin", "hello"], src: "Resume",
        a: "You can email srivastavadya@gmail.com, find code at github.com/Adya6714, or download the resume with the button at the top of the page." }
    ],
    fallback: "I'm not sure I have a good answer for that one. Email me at srivastavadya@gmail.com, or try one of the interview threads above."
  }
};
