/* All site content lives here. Edit this file to change text, links, projects, notes and the shelf. */
window.CONTENT = {
  person: {
    name: "Adya Srivastava",
    photo: "assets/photo.jpg",
    intro: [
      "I'm Adya — I build AI/ML systems end to end: take a fuzzy question, run the experiments, break what doesn't hold up, and ship what does. Research for the hard questions; engineering for making the answer real.",
      "I'm looking for ML research and engineering roles, and I'm always glad to talk — a hackathon idea, a paper I should read, a different take on the field, or just hello. If you're building something interesting, drop me a note."
    ],
    openTo: ["ML research and engineering roles", "Hackathon teammates", "Resources you think I should know", "Conversations about AI/ML"],
    closingTitle: "At the core, I like making things.",
    closing: [
      "At the core, I like making things. I like starting with a blank page, learning whatever I need to learn, and slowly turning an idea into something real. Research gives me the opportunity to chase questions that don't have obvious answers, while engineering gives me the satisfaction of actually building the answer. AI and ML happen to sit at a particularly exciting intersection of the two for me.",
      "I don't think of learning as something that ends when you understand the theory. I want to understand enough to build with it, break it, question it, and hopefully discover something that wasn't obvious before. That's probably what keeps me moving between research papers, experiments, systems, and completely new things I know very little about. There's always something more to uncover, and that's the part I enjoy most."
    ],
    email: "srivastavadya@gmail.com",
    github: "https://github.com/Adya6714",
    linkedin: "https://www.linkedin.com/in/adyasri",
    openreview: "https://openreview.net/forum?id=d8w4gMVQ1w"
  },

  suggest: {
    title: "Drop me a card",
    blurb: "Ideas I should explore, resources I should read, a hackathon you'd like a teammate for, or anything you think I should know. Anonymous is fine.",
    placeholder: "A suggestion, a resource, a hackathon idea, or just hello",
    sendLabel: "Send card",
    types: ["Suggestion", "Resource", "Hackathon", "Opportunity", "Just saying hi"],
    thankYou: [
      "Got it. Thank you for taking the time.",
      "Your card made it to me. I really appreciate it.",
      "Thank you. This kind of note genuinely makes my day.",
      "Received. I'll read this properly.",
      "Thanks for dropping this in. Means a lot.",
      "Noted with care. Thank you for reaching out."
    ]
  },

  research: [
    {
      id: "r-reasoning",
      tag: "Reasoning",
      status: "CAISc 2026",
      title: "Same Score, Different Strategy",
      question:
        "When two AI models get the same score, are they solving problems the same way?",
      note: {
        what: "Tells whether an AI model solved a problem or remembered it.",
        headline: "1.00 to 0.00",
        caption: "after a simple rename",
      },
      did: "Built three probes (rename and rewording, plan versus execution, closeness to training data) and ran 219 problems across arithmetic, planning and optimisation on five frontier models, about 20,000 API calls, with exact answer checkers.",
      found: [
        "Models with matching scores break in very different ways.",
        "Accepting an injected wrong step 88 to 100% of the time did not predict whether a model finished correctly.",
        "Even with three probes, 61.6% of problems resist a clean label, so behaviour alone is not enough.",
      ],
      next: "Look inside the models: where the split between recalling and computing happens, and which training conditions create it.",
      builtFrom: "retrieval-vs-computation",
      links: [
        ["Paper", "https://openreview.net/forum?id=d8w4gMVQ1w"],
        ["Project page", "https://adya6714.github.io/retrieval-vs-computation/"],
        ["Code", "https://github.com/Adya6714/retrieval-vs-computation"],
      ],
    },
    {
      id: "r-vision",
      tag: "Vision",
      status: "Preprint",
      title: "Reading Without Looking",
      question:
        "When an OCR model says it is confident, is it actually looking at the page?",
      note: {
        what: "Checks whether an OCR model's confidence comes from the page.",
        headline: "0.99",
        caption: "confidence on a blank page",
      },
      did: "Trained a small OCR model from scratch for Indian scripts so every internal step could be inspected, then tested it with blank, noisy and scrambled pages, and checked the findings on a production OCR system.",
      found: [
        "Confidence tracked language patterns, not the image.",
        "Confidence that looked useful on familiar pages (AUROC 0.84) fell to near chance on new ones (0.57).",
        "Routing pages by confidence alone can send exactly the wrong pages through.",
      ],
      next: "Confidence scores that check whether the image actually supports the answer.",
      builtFrom: "vlm-ocr-eval",
      links: [
        ["Project page", "https://adya6714.github.io/vlm-ocr-eval/"],
        ["Preprint", "https://adya6714.github.io/vlm-ocr-eval/paper/main.pdf"],
        ["Code", "https://github.com/Adya6714/vlm-ocr-eval"],
      ],
    },
    {
      id: "r-markets",
      tag: "Markets",
      status: "Preprint",
      title:
        "Diffusion-Generated Volatility Surfaces for RL Hedging of NIFTY 50 Barrier Options",
      question:
        "Can AI-generated market data train a better hedging agent, and how much of the gain comes from the data versus the agent?",
      note: {
        what: "Trains a hedging agent on AI-generated market data.",
        headline: "60.1%",
        caption: "lower tail-risk hedging error",
      },
      did: "Built 1,268 NIFTY 50 volatility surfaces from 912K+ option records, trained a diffusion model to generate new ones, and trained a reinforcement learning agent to hedge barrier options on them.",
      found: [
        "Generated surfaces had fewer pricing inconsistencies than real data (0.005 vs 0.009).",
        "The agent cut CVaR(95%) hedging error by 60.1% against Black-Scholes.",
        "A model-risk decomposition separates the gain from better data and from a better agent.",
      ],
      next: "Testing across market regimes and other indices.",
      builtFrom: "ddpm-vol-hedging",
      links: [
        [
          "Paper (PDF)",
          "https://github.com/Adya6714/ddpm-vol-hedging/blob/main/paper/Volatility_Surfaces_Research.pdf",
        ],
        ["Code", "https://github.com/Adya6714/ddpm-vol-hedging"],
      ],
    },
    {
      id: "r-quantum",
      tag: "Quantum",
      status: "Preprint",
      title:
        "Hybrid Quantum-Classical Paradigms for Nonlinear Dynamics, Machine Learning and Autonomous Systems: A Unified Framework",
      question:
        "Where can quantum and classical computing work together on problems neither handles well alone?",
      note: {
        what: "Maps how quantum and classical computing can work together.",
        headline: "6 topics",
        caption: "in one framework",
      },
      did: "A survey that connects methods for simulating nonlinear systems on quantum hardware, quantum approaches to learning and control, and a comparison of hardware and energy efficiency.",
      found: [
        "Covers Carleman linearization, quantum Fokker-Planck embedding, variational algorithms for PDEs, quantum reinforcement learning and quantum game theory.",
        "Compares hardware platforms and energy efficiency in one place.",
      ],
      next: "Turning the survey's open problems into small experiments.",
      builtFrom: null,
      links: [
        [
          "Paper (PDF)",
          "https://drive.google.com/file/d/1zwhnW2Nvl6I5myx556UoGED-1MKv9qt5/view?usp=sharing",
        ],
      ],
    },
  ],

  projects: [
    { id: "p-mesh", title: "OmniMesh", group: "AI systems", featured: true,
      site: "https://omnimesh-command.web.app",
      thumb: "https://opengraph.githubassets.com/1/Adya6714/OmniMesh",
      line: "An offline disaster-triage network: phones relay emergencies by severity when the internet is down, and AI drafts the dispatch plan.",
      skills: ["Kotlin", "Android (Jetpack Compose)", "Firebase", "Gemini", "P2P networking"],
      problem: "In disasters, internet and cell networks fail first ,  exactly when responders need to coordinate and triage by severity.",
      built: ["Android phones act as triage nodes in an offline-first, peer-to-peer mesh.", "An AI command backend drafts dispatch plans by severity.", "Sync to the cloud once connectivity returns."],
      impact: "Keeps communication and decision support working when infrastructure is down.",
      links: { live: "https://omnimesh-command.web.app", code: "https://github.com/Adya6714/OmniMesh" } },
    { id: "p-fsense", title: "FraudSense AI", group: "AI systems", featured: true,
      thumb: "https://opengraph.githubassets.com/1/Adya6714/FraudSense-AI",
      line: "Catches AI-assisted cheating in interviews by combining writing signals, typing behaviour and an LLM judge; flags only when 3 independent signals agree.",
      skills: ["DetectGPT", "NLP", "Keystroke biometrics", "Streamlit", "Python"],
      problem: "Candidates can read LLM-generated answers during a live interview, and a single detector is too noisy to trust alone.",
      built: ["Fuses writing signals, keystroke behaviour and an LLM judge.", "Flags a candidate only when at least three independent signal types agree."],
      impact: "Gives interviewers a combined signal instead of a single brittle detector.",
      links: { code: "https://github.com/Adya6714/FraudSense-AI" } },
    { id: "p-fraud", title: "FraudScope360", group: "AI systems", featured: true,
      thumb: "https://opengraph.githubassets.com/1/Adya6714/FraudScope360",
      line: "Fraud detection with five independent detectors (anomalies, sudden behaviour changes, fraud networks, identity clusters, text) fused into one risk score. National winner, Citi Innovation Challenge.",
      skills: ["Isolation Forest", "Node2Vec", "DBSCAN", "Kafka", "FastAPI"],
      problem: "Fraud rarely looks suspicious one account at a time ,  it shows up in connections between accounts, identities and behaviour.",
      built: ["Five modules: anomalies, behaviour shifts, fraud networks, identity clusters and text.", "Fused into one risk score and served through FastAPI."],
      impact: "National winner, Citi Innovation Challenge. Combines several weak signals into one decision.",
      links: { code: "https://github.com/Adya6714/FraudScope360" } },
    { id: "p-social", title: "ContentPulse", group: "AI systems", featured: true,
      site: "https://social-analyzer-six.vercel.app/",
      thumb: "https://opengraph.githubassets.com/1/Adya6714/social-analyzer",
      line: "Upload a social media post as text, image or PDF and get structured engagement feedback from Gemini.",
      skills: ["Gemini API", "OCR", "FastAPI", "React", "Vercel", "Railway"],
      problem: "Creators need concrete feedback on posts, not a single vanity score.",
      built: ["PDF, image (OCR) and raw text intake.", "Gemini-backed structured JSON feedback.", "Frontend on Vercel, API on Railway."],
      impact: "A production path from messy post content to readable engagement advice.",
      links: { live: "https://social-analyzer-six.vercel.app/", code: "https://github.com/Adya6714/social-analyzer" } },
    { id: "p-pdf", title: "PDF Extractor", group: "AI systems", featured: false,
      thumb: "https://opengraph.githubassets.com/1/Adya6714/pdf_extractor",
      line: "Pulls the structure out of any PDF, then finds the sections that matter for a given reader.",
      skills: ["Document AI", "NLP", "Docker"],
      problem: "Long PDFs bury the sections a given reader actually needs.",
      built: ["Hierarchical outline extraction.", "Persona-based semantic selection.", "Dockerised batch processing."],
      impact: "Structured outlines plus reader-aware highlights from the same PDF stack.",
      links: { code: "https://github.com/Adya6714/pdf_extractor" } },
    { id: "p-traffic", title: "GridLock 2.0: Traffic Demand Prediction", group: "Forecasting and data", featured: true,
      thumb: "https://opengraph.githubassets.com/1/Adya6714/traffic-prediction",
      line: "Predicts traffic demand for every map cell and 15-minute slot; scored 87.9 (100 × R²) with a reproducible ensemble.",
      skills: ["Spatiotemporal forecasting", "Gradient boosting", "Ensembling"],
      problem: "Traffic demand varies sharply across space and time; a model has to respect both.",
      built: ["Competition pipeline for geohash × slot demand forecasting.", "Reproducible ensemble with no external data.", "Leaderboard score 87.90."],
      impact: "A clean baseline for short-horizon traffic demand under competition constraints.",
      links: { code: "https://github.com/Adya6714/traffic-prediction" } },
    { id: "p-routecast", title: "RouteCast360", group: "Forecasting and data", featured: false,
      thumb: "https://opengraph.githubassets.com/1/Adya6714/RouteCast360",
      line: "Forecasts how many seats will sell on intercity bus routes from booking and search signals.",
      skills: ["CatBoost", "Target encoding", "GroupKFold"],
      problem: "Operators need final seat counts before departure, from noisy search and booking streams.",
      built: ["CatBoost regression with target encodings and calendar features.", "GroupKFold evaluation by day-of-year."],
      impact: "Turns booking and search history into a route-level demand forecast.",
      links: { code: "https://github.com/Adya6714/RouteCast360" } },
    { id: "p-price", title: "SmartPricing360", group: "Forecasting and data", featured: false,
      thumb: "https://opengraph.githubassets.com/1/Adya6714/smart-pricing360",
      line: "Multimodal e-commerce price predictor: text (e5), vision (CLIP) and gradient boosting, OOF SMAPE 49.77.",
      skills: ["Machine learning", "CLIP", "LightGBM", "Pricing"],
      problem: "Catalog price depends on both listing text and imagery that single-modality models miss.",
      built: ["Text embeddings with attention pooling (e5-small-v2).", "CLIP image embeddings with test-time augmentation.", "LightGBM-Tweedie plus a two-stage ensemble."],
      impact: "Hackathon multimodal pricing stack with documented setup and reproducible OOF metrics.",
      links: { code: "https://github.com/Adya6714/smart-pricing360" } },
    { id: "p-ganga", title: "Ganga MRV", group: "Forecasting and data", featured: true,
      site: "https://site-eight-khaki-34.vercel.app",
      thumb: "https://opengraph.githubassets.com/1/Adya6714/ganga-mrv",
      line: "Checks whether soil data supports a carbon-removal credit: a full measure, report and verify pipeline with a teaching book.",
      skills: ["Data analysis", "Statistics", "Python"],
      problem: "Carbon-removal credits need measurement that survives counterfactuals, not just a single before/after delta.",
      built: ["Full MRV pipeline on a synthetic Project Ganga dataset.", "Five methods that agree the credit claim fails.", "Teaching book plus a live dashboard."],
      impact: "Shows how to reject a credit with transparent, reproducible checks.",
      links: { live: "https://site-eight-khaki-34.vercel.app", code: "https://github.com/Adya6714/ganga-mrv" } },
    { id: "p-dim", title: "Data in Motion", group: "Products and platforms", featured: false,
      thumb: "https://opengraph.githubassets.com/1/Adya6714/data-in-motion",
      line: "Decides which cloud storage tier each file belongs in using optimisation and ML, and moves it automatically.",
      skills: ["MILP", "scikit-learn", "Kafka (Redpanda)", "FastAPI", "Docker"],
      problem: "Storage tiers and regions trade off cost against latency, and the right placement changes as access patterns change.",
      built: ["A mixed-integer program chooses placement.", "A Kafka pipeline carries out migrations."],
      impact: "Turns storage placement into an optimisation problem rather than a manual decision.",
      links: { code: "https://github.com/Adya6714/data-in-motion" } },
    { id: "p-meme", title: "Meme Coin Aggregator", group: "Products and platforms", featured: false,
      thumb: "https://opengraph.githubassets.com/1/Adya6714/meme-coin-aggregator",
      line: "One real-time API for meme-coin data from several exchanges, with caching and live updates.",
      skills: ["TypeScript", "WebSockets", "Caching"],
      problem: "Token data is scattered across DexScreener, GeckoTerminal and similar feeds.",
      built: ["Unified API with caching, deduplication, sorting and pagination.", "WebSocket updates for live token streams."],
      impact: "One backend surface for meme-coin market data.",
      links: { code: "https://github.com/Adya6714/meme-coin-aggregator" } },
    { id: "p-ondc", title: "ONDC Food Platform", group: "Products and platforms", featured: false,
      thumb: "https://opengraph.githubassets.com/1/Adya6714/ONDC-Food-Platform",
      line: "Connects farmers, restaurants and food banks, with demand prediction to cut food waste.",
      skills: ["Python", "Demand forecasting"],
      problem: "Surplus food and demand sit in different systems with little shared inventory logic.",
      built: ["User types for farmer, restaurant and food bank.", "Inventory management and simple demand prediction."],
      impact: "A starter backend for food redistribution on an ONDC-like network.",
      links: { code: "https://github.com/Adya6714/ONDC-Food-Platform" } },
    { id: "p-cw", title: "CloudWatch in Plain English", group: "AI systems", featured: false, private: true,
      line: "Ask AWS metrics questions in plain English and get charts back.",
      skills: ["AWS Bedrock", "Embeddings", "Lambda"],
      problem: "Finding the right CloudWatch metric means knowing its exact name and digging through the console or CLI.",
      built: ["Bedrock agent with embeddings over metric descriptions.", "Lambda cosine match, then live charts.", "npm package with a cross-account CDK construct."],
      impact: "Query metrics in plain language without a managed vector database.",
      links: {} },
    { id: "p-rvc", title: "Retrieval vs Computation (code)", group: "Research code", featured: false,
      site: "https://adya6714.github.io/retrieval-vs-computation/",
      thumb: "https://opengraph.githubassets.com/1/Adya6714/retrieval-vs-computation", researchId: "r-reasoning",
      line: "Evaluation toolkit behind the CAISc paper.",
      skills: ["LLM evaluation", "Python"],
      problem: "Benchmark scores cannot tell whether a model recalled a template or worked the problem out.",
      built: ["Probes, checkers and reproducible pipelines for the Same Score, Different Strategy paper."],
      impact: "Open code and site for the research thread ,  open Research for the full story.",
      links: { live: "https://adya6714.github.io/retrieval-vs-computation/", code: "https://github.com/Adya6714/retrieval-vs-computation", paper: "https://openreview.net/forum?id=d8w4gMVQ1w" } },
    { id: "p-ocr", title: "vlm-ocr-eval (code)", group: "Research code", featured: false,
      site: "https://adya6714.github.io/vlm-ocr-eval/",
      thumb: "https://opengraph.githubassets.com/1/Adya6714/vlm-ocr-eval", researchId: "r-vision",
      line: "From-scratch Indic OCR instrument and probes.",
      skills: ["PyTorch", "OCR"],
      problem: "OCR confidence can look high even when the model is not looking at the page.",
      built: ["From-scratch Indic OCR model and blank/noise/scramble probes."],
      impact: "Open code and site for the Vision research thread.",
      links: { live: "https://adya6714.github.io/vlm-ocr-eval/", code: "https://github.com/Adya6714/vlm-ocr-eval", paper: "https://adya6714.github.io/vlm-ocr-eval/paper/main.pdf" } },
    { id: "p-ddpm", title: "ddpm-vol-hedging (code)", group: "Research code", featured: false,
      thumb: "https://opengraph.githubassets.com/1/Adya6714/ddpm-vol-hedging", researchId: "r-markets",
      line: "Diffusion and RL hedging code.",
      skills: ["Diffusion models", "RL"],
      problem: "Hedging agents need more market scenarios than history provides.",
      built: ["Diffusion generator for NIFTY volatility surfaces and a PPO hedging agent."],
      impact: "Open code for the Markets research thread.",
      links: { code: "https://github.com/Adya6714/ddpm-vol-hedging", paper: "https://github.com/Adya6714/ddpm-vol-hedging/blob/main/paper/Volatility_Surfaces_Research.pdf" } },
    { id: "p-wml", title: "WML: Who's Most Like", group: "Early work", featured: false,
      site: "https://wml-ten.vercel.app",
      thumb: "https://opengraph.githubassets.com/1/Adya6714/WML",
      line: "A party game: draw a word, tag the friend who fits it, with a live leaderboard.",
      skills: ["React", "Flask"],
      problem: "Need a fast social icebreaker that still has a live leaderboard.",
      built: ["Word pool with skip/return.", "Friend profiles and auto-updating leaderboard."],
      impact: "A deployed playful game for small groups.",
      links: { live: "https://wml-ten.vercel.app", code: "https://github.com/Adya6714/WML" } },
    { id: "p-psms", title: "PSMS", group: "Early work", featured: false,
      thumb: "https://opengraph.githubassets.com/1/Adya6714/PSMS",
      line: "Project and service management system: React frontend with a Python API for tracking work.",
      skills: ["JavaScript", "React", "Python"],
      problem: "Small teams need a lightweight place to track projects and services without heavy SaaS.",
      built: ["Create React App frontend.", "Python backend API for project and service records."],
      impact: "An early full-stack ops UI ,  useful as a learning scaffold more than a product claim.",
      links: { code: "https://github.com/Adya6714/PSMS" } },
    { id: "p-tasks", title: "Task Board", group: "Early work", featured: false,
      site: "https://task-board-app-bay.vercel.app",
      thumb: "https://opengraph.githubassets.com/1/Adya6714/task-board-app",
      line: "Kanban-style personal task board with a React frontend and a small backend.",
      skills: ["JavaScript", "React", "Vite"],
      problem: "Simple personal task tracking without a heavy SaaS board.",
      built: ["Vite + React board UI.", "Backend for persisting cards.", "Deployed on Vercel."],
      impact: "A lightweight day-to-day board from early full-stack practice.",
      links: { live: "https://task-board-app-bay.vercel.app", code: "https://github.com/Adya6714/task-board-app" } },
    { id: "p-atari", title: "Atari RL Agent", group: "Early work", featured: false,
      thumb: "https://opengraph.githubassets.com/1/Adya6714/Atari-game-RL-Agent",
      line: "My first reinforcement learning project and a log of how I learned ML.",
      skills: ["Reinforcement learning", "Python"],
      problem: "Learn deep Q-learning end to end on a visual game environment.",
      built: ["CNN-based DQN pipeline on Atari frames.", "Study notes tied to early RL learning."],
      impact: "Hands-on DQN baseline from the start of the RL path.",
      links: { code: "https://github.com/Adya6714/Atari-game-RL-Agent" } }
  ],

  jobs: [
    {
      id: "j-kat",
      co: "Khageshvara Aviation",
      role: "Product Development Lead and ML Intern",
      when: "May to Oct 2023",
      flagText: "Khageshvara",
      stoneText: "Drone vision that spots people",
      stone: [640, 760],
      color: "#7ec8e8",
      bullets: [
        "Built CNN vision pipelines for real-time human detection from drones.",
        "Built the financial model and pitch behind a successful DST funding round.",
      ],
      impact: ["Real-time person detection from aerial video", "Funding secured"],
      skills: ["Computer vision", "CNNs", "OpenCV"],
    },
    {
      id: "j-grasim",
      co: "Grasim (Aditya Birla Group)",
      role: "Research Engineer",
      when: "May to Jul 2024",
      flagText: "Grasim",
      stoneText: "Sensors and industrial control",
      stone: [690, 700],
      color: "#e8c07a",
      bullets: [
        "Designed 20+ PLC simulations for autonomous control and safety validation.",
        "Built IR and IoT sensor networks for real-time monitoring on site.",
      ],
      impact: ["98% detection accuracy on the monitoring task", "20+ simulations"],
      skills: ["IoT", "PLC", "Sensors"],
    },
    {
      id: "j-fidel",
      co: "FidelFolio Investments",
      role: "Quant Investment Analyst",
      when: "May to Jun 2025",
      flagText: "FidelFolio",
      stoneText: "Portfolio research, Sharpe up 42%",
      stone: [745, 610],
      color: "#c4b4f0",
      bullets: [
        "Built a research workflow for portfolio analytics and Sharpe evaluation.",
        "Used genetic algorithms and Bayesian optimisation for risk-aware portfolios.",
        "Analysed 24 factors across 200+ portfolios.",
      ],
      impact: ["Sharpe up about 42%", "Research efficiency up 90%"],
      skills: [
        "Portfolio optimisation",
        "Factor models",
        "Bayesian optimisation",
      ],
    },
    {
      id: "j-nurix",
      co: "Nurix AI",
      role: "ML Engineering Intern",
      when: "Jul to Dec 2025",
      flagText: "Nurix AI",
      stoneText: "Speech AI in production",
      stone: [715, 470],
      color: "#6fd4c8",
      bullets: [
        "Built and deployed a TinyBERT voicemail detector with backend integration.",
        "Designed a word-error correction pipeline using Word2Vec, phonetic normalisation and LLM scoring.",
        "Improved real-time turn-end detection in a transformer speech-to-text pipeline.",
      ],
      impact: ["95% precision on voicemail detection", "40% fewer word errors"],
      skills: ["Transformers", "Speech", "Deployment", "NLP"],
    },
  ],

  skills: [
    ["LLMs and NLP", ["PyTorch", "Transformers", "LLM evaluation", "Probing and ablation", "LangChain", "Gemini API"]],
    ["Vision and documents", ["OpenCV", "OCR", "CNNs", "Document AI"]],
    ["Generative and RL", ["Diffusion models", "PPO", "vLLM"]],
    ["Classical ML and forecasting", ["XGBoost", "CatBoost", "scikit-learn", "Graph ML (Node2Vec)", "Anomaly detection"]],
    ["Systems", ["Python", "FastAPI", "Docker", "Kafka", "AWS", "GCP", "Firebase", "SQL", "TypeScript", "Kotlin"]],
    ["Quant", ["Portfolio optimisation", "Volatility modelling", "CVaR", "Backtesting"]]
  ],

  library: {
    studyModule: {
      title: "My ML study book",
      description: "The notes, derivations and experiments I'm writing for myself while learning ML properly.",
      // Paste a Drive "Anyone with the link" URL here (not drive.google.com/drive/home).
      link: "",
      chapters: [
        "Probability and linear algebra refreshers",
        "Transformers from the ground up",
        "Evaluation and probing methods",
        "Diffusion and generative models",
        "RL for control and hedging"
      ]
    },
    leetcode: "",
    videos: [
      { t: "Let's build GPT from scratch", by: "Andrej Karpathy", len: "1h 56m", url: "https://www.youtube.com/watch?v=kCc8FmEb1nY", why: "Best hands-on walkthrough of attention and training a tiny GPT." },
      { t: "Attention in transformers, visually explained", by: "3Blue1Brown", len: "26 min", url: "https://www.youtube.com/watch?v=eMlx5fFNoYc", why: "Clearest visual intuition for Q/K/V." }
    ],
    reading: [
      { t: "Attention Is All You Need", by: "Vaswani et al.", url: "https://arxiv.org/abs/1706.03762", why: "The original architecture paper." },
      { t: "A Mathematical Framework for Transformer Circuits", by: "Elhage et al.", url: "https://transformer-circuits.pub/2021/framework/index.html", why: "Language for talking about circuits inside transformers." },
      { t: "Toy Models of Superposition", by: "Elhage et al.", url: "https://transformer-circuits.pub/2022/toy_model/index.html", why: "Why features pack into fewer dimensions." },
      { t: "Denoising Diffusion Probabilistic Models", by: "Ho, Jain, Abbeel", url: "https://arxiv.org/abs/2006.11239", why: "Foundation for the volatility-surface work." },
      { t: "What are diffusion models?", by: "Lilian Weng", url: "https://lilianweng.github.io/posts/2021-07-11-diffusion-models/", why: "Clean survey before reading the DDPM paper." },
      { t: "Reinforcement Learning: An Introduction", by: "Sutton and Barto", url: "http://incompleteideas.net/book/the-book.html", why: "Reference for the hedging RL agent." }
    ],
    notes: []
  },

  meraki: {
    about: "Meraki is where I write about experiences, lessons and the way I see the world. Mostly poems, some stories.",
    site: "https://srivastavadya.wixsite.com/meraki14",
    posts: [
      { t: "Justice of Time", d: "Nov 16, 2023", min: 2, url: "https://srivastavadya.wixsite.com/meraki14/post/justice-of-time", note: "But, there will be a time… when the sun would bleed in red…" },
      { t: "Laughingly", d: "Nov 15, 2023", min: 1, url: "https://srivastavadya.wixsite.com/meraki14/post/laughingly", note: "Amidst the cluster, I stood in ,  a smile had my face covered…" },
      { t: "Birth of an Evil", d: "Nov 15, 2023", min: 3, url: "https://srivastavadya.wixsite.com/meraki14/post/birth-of-an-evil", note: "As the clouds of the night swept the sky…" },
      { t: "Stupidity", d: "Nov 15, 2023", min: 1, url: "https://srivastavadya.wixsite.com/meraki14/post/stupidity", note: "Two sides of selfishness ,  an unnecessary evil." },
      { t: "Hallucinate the Ricochet", d: "Nov 15, 2023", min: 6, url: "https://srivastavadya.wixsite.com/meraki14/post/hallucinate-the-ricochet", note: "A poem as story ,  too proud to believe life flashes before death." },
      { t: "Two", d: "Nov 15, 2023", min: 1, url: "https://srivastavadya.wixsite.com/meraki14/post/__two", note: "Two are the coconuts knocking… two are the stars twinkling…" },
      { t: "The Right Path", d: "Nov 15, 2023", min: 1, url: "https://srivastavadya.wixsite.com/meraki14/post/the-right-path", note: "As I was walking through the lane, darkness stayed with me…" },
      { t: "Soon...", d: "Jul 25, 2023", min: 2, url: "https://srivastavadya.wixsite.com/meraki14/post/_soon", note: "And I know for a fact we'd be sitting on the stairs…" },
      { t: "Heaven", d: "Apr 20, 2023", min: 2, url: "https://srivastavadya.wixsite.com/meraki14/post/heaven", note: "There is no ultimate that ever existed…" },
      { t: "Shielded", d: "Mar 13, 2023", min: 2, url: "https://srivastavadya.wixsite.com/meraki14/post/shielded", note: "To be young is a boon ,  for the euphoria sparked inside…" },
      { t: "Lustre", d: "Mar 8, 2023", min: 1, url: "https://srivastavadya.wixsite.com/meraki14/post/lustre", note: "As she sat on her balcony…" },
      { t: "The Little Boy", d: "Mar 8, 2023", min: 1, url: "https://srivastavadya.wixsite.com/meraki14/post/the-little-boy", note: "With the children playing in the park…" },
      { t: "Twinkling", d: "Mar 7, 2023", min: 1, url: "https://srivastavadya.wixsite.com/meraki14/post/twinkling", note: "Goodness is not kindness…" }
    ]
  },

  otherWork: [
    { t: "Citizen Services App", type: "Case study", line: "Civic services product write-up.", url: "assets/case-studies/citizen-services-app.pdf" },
    { t: "Cloud Computing in Healthcare", type: "Case study", line: "Cloud patterns in clinical workflows.", url: "assets/case-studies/cloud-computing-healthcare.pdf" },
    { t: "Zepto assignment", type: "Assignment", line: "Quick-commerce operations case.", url: "assets/case-studies/zepto-assignment.pdf" },
    { t: "Consulting case", type: "Case study", line: "Structured consulting analysis.", url: "assets/case-studies/consulting-case.pdf" },
    { t: "Business case study", type: "Case study", line: "Case framing and recommendation.", url: "assets/case-studies/business-case-study.pdf" },
    { t: "Idea guidebook", type: "Guide", line: "Scoping a rough idea into a product.", url: "assets/case-studies/idea-guidebook.pdf" },
    { t: "Pitch deck", type: "Deck", line: "Startup-style pitch narrative.", url: "assets/case-studies/pitch-deck.pdf" },
    { t: "TAS write-up", type: "Write-up", line: "Systems analysis notes.", url: "assets/case-studies/tas.pdf" },
    { t: "MT assignment", type: "Assignment", line: "Course technical write-up.", url: "assets/case-studies/mt-assignment.pdf" }
  ],

  shelf: {
    tabs: ["Skills", "Study module", "Watching and reading", "Practice", "Beyond ML"],
    skills: null, /* use top-level C.skills */
    studyModule: {
      title: "My ML study book",
      description: "The notes, derivations and experiments I am writing for myself while learning ML properly.",
      url: "",
      chapters: [
        "Probability and linear algebra refreshers",
        "Transformers from the ground up",
        "Evaluation and probing methods",
        "Diffusion and generative models",
        "RL for control and hedging"
      ]
    },
    watching: [
      { videoId: "kCc8FmEb1nY", title: "Let's build GPT from scratch", by: "Andrej Karpathy", type: "Video", why: "Best hands-on walkthrough of attention and training a tiny GPT.", url: "https://www.youtube.com/watch?v=kCc8FmEb1nY" },
      { videoId: "eMlx5fFNoYc", title: "Attention in transformers, visually explained", by: "3Blue1Brown", type: "Video", why: "Clearest visual intuition for Q/K/V.", url: "https://www.youtube.com/watch?v=eMlx5fFNoYc" },
      { videoId: "", title: "Attention Is All You Need", by: "Vaswani et al.", type: "Paper", why: "The original architecture paper.", url: "https://arxiv.org/abs/1706.03762" },
      { videoId: "", title: "A Mathematical Framework for Transformer Circuits", by: "Elhage et al.", type: "Paper", why: "Language for talking about circuits inside transformers.", url: "https://transformer-circuits.pub/2021/framework/index.html" },
      { videoId: "", title: "Toy Models of Superposition", by: "Elhage et al.", type: "Paper", why: "Why features pack into fewer dimensions.", url: "https://transformer-circuits.pub/2022/toy_model/index.html" },
      { videoId: "", title: "Denoising Diffusion Probabilistic Models", by: "Ho, Jain, Abbeel", type: "Paper", why: "Foundation for the volatility-surface work.", url: "https://arxiv.org/abs/2006.11239" },
      { videoId: "", title: "What are diffusion models?", by: "Lilian Weng", type: "Blog", why: "Clean survey before reading the DDPM paper.", url: "https://lilianweng.github.io/posts/2021-07-11-diffusion-models/" },
      { videoId: "", title: "Reinforcement Learning: An Introduction", by: "Sutton and Barto", type: "Book", why: "Reference for the hedging RL agent.", url: "http://incompleteideas.net/book/the-book.html" }
    ],
    practice: { leetcode: "", kaggle: "https://www.kaggle.com/adyasrivastava" },
    beyond: [
      { title: "Meraki", line: "Poems and short stories. An alleyway to sonder.", href: "writing.html", external: "https://srivastavadya.wixsite.com/meraki14" },
      { title: "Case studies", line: "Consulting and non-ML work.", href: "other.html" }
    ]
  },

  guardian: {
    intro: "Hi, I am the guardian of this river. Interview Adya through me: her research, internships, projects, skills, or what she is looking for next. I answer only from her own notes and papers.",
    chips: [
      ["Walk me through your research", "research"],
      ["What did you ship at Nurix?", "nurix"],
      ["Tell me about the OCR project", "ocr"],
      ["Why should we hire you?", "hire"],
      ["What are you looking for?", "looking"],
      ["How do you work on a team?", "team"]
    ],
    kb: [
      { id: "research", keys: ["research", "paper", "caisc", "reasoning", "retrieval", "computation", "fragility", "strategy", "llm", "llms", "probe", "probes", "interview"], src: "Paper abstract, project page",
        a: "My main research asks: when two LLMs get the same benchmark score, are they solving problems the same way? In Same Score, Different Strategy (CAISc 2026) I used three probes (entity rename, plan-versus-execution consistency, and closeness to training data) on 219 problems across arithmetic, planning and optimisation, with five models. Matched accuracy hid large differences: o3-mini went from a perfect score to zero on weighted interval scheduling after a rename. It is the first paper in a four-paper program on where retrieval and computation split inside models." },
      { id: "ocr", keys: ["ocr", "confidence", "indic", "vlm", "vision", "grounding", "calibration", "reading"], src: "Reading Without Looking project page",
        a: "Reading Without Looking tests whether OCR confidence reflects what the model sees. I trained a small OCR model from scratch so I could blank the image, add noise, scramble it and switch off the vision pathway. Confidence stayed around 0.9 while the correct first character had roughly 1e-11 probability, and a blank page got almost the same confidence as text. On held-out lines AUROC fell from 0.84 to about 0.57. The takeaway is that peak confidence is not a safe routing signal." },
      { id: "nurix", keys: ["nurix", "intern", "internship", "speech", "voicemail", "stt", "wer", "production", "shipped", "ship"], src: "Resume",
        a: "At Nurix AI (Jul to Dec 2025) I worked on production speech and NLP. I built and deployed a TinyBERT plus neural network voicemail detector with backend integration (95% precision), improved turn-end detection in a transformer speech-to-text pipeline using semantic parsing, and designed a word-error correction pipeline using Word2Vec, phonetic normalisation and LLM scoring that cut WER by 40%." },
      { id: "quant", keys: ["quant", "fidelfolio", "finance", "portfolio", "sharpe", "hedging", "ddpm", "diffusion", "volatility", "ppo", "nifty"], src: "Resume, project write-up",
        a: "On the finance side I did quant research at FidelFolio (portfolio optimisation with genetic algorithms and Bayesian optimisation, Sharpe up about 42%). I am also writing a paper that trains a diffusion model on 1,268 NIFTY 50 volatility surfaces to generate new market scenarios, then trains a PPO agent to hedge barrier options on them. It cut CVaR(95%) hedging error by 60.1% against Black-Scholes and is compared with a Heston-trained RL baseline." },
      { id: "agents", keys: ["agent", "agents", "agentic", "cloudwatch", "aws", "omnimesh", "mesh", "offline", "disaster", "gemma", "vllm"], src: "Project write-ups",
        a: "On the systems side: OmniMesh is an offline disaster-response mesh where phones act as triage nodes, backed by a six-agent FastAPI service serving Gemma-2-9B with vLLM on an AMD GPU. CloudWatch in Plain English lets teams query AWS metrics in natural language using a Bedrock agent, embeddings in S3 and semantic search in Lambda." },
      { id: "fraud", keys: ["fraud", "fraudscope", "citi", "hackathon", "winner", "graph", "fraudsense"], src: "Resume",
        a: "FraudScope360 won the national round of the Citi Bank Campus Innovation Challenge. It is a five-module fraud engine combining graph machine learning, anomaly detection and XGBoost, covering fraud rings and identity fraud, served through FastAPI." },
      { id: "edu", keys: ["bits", "education", "college", "degree", "graduate", "university", "studied", "background"], src: "Resume",
        a: "I graduated from BITS Pilani in 2026 with a B.E. in Electrical and Electronics Engineering and a minor in Finance." },
      { id: "stack", keys: ["stack", "tools", "skills", "pytorch", "python", "languages", "framework", "frameworks", "strength"], src: "Resume",
        a: "Day to day: Python and PyTorch, with Transformers, scikit-learn and XGBoost. For systems work I use FastAPI, Docker, vLLM and AWS or GCP. I have also used OpenCV, LangChain, C++, SQL and TypeScript." },
      { id: "looking", keys: ["looking", "role", "roles", "hire", "hiring", "available", "job", "seeking", "want", "interested", "interests", "next", "open"], src: "Resume, profile",
        a: "I am looking for ML research and research engineering roles where I can build, run experiments and learn from people working on hard problems. My interests are LLM evaluation and reasoning, model internals and interpretability, and post-training and alignment." },
      { id: "hire", keys: ["hire", "why you", "strengths", "fit", "candidate", "offer", "value"], src: "Resume, papers",
        a: "I ship: a CAISc paper on LLM reasoning fragility, production speech work at Nurix that cut WER by 40%, and a national Citi Innovation win. I care about whether a metric actually means what people think it means ,  so I design probes and ablations, not only dashboards. I am comfortable moving between research and engineering." },
      { id: "team", keys: ["team", "collaborate", "collaboration", "work with", "communication", "mentor", "style"], src: "Experience write-ups",
        a: "I like clear write-ups and small demos that make a result checkable. At Nurix I worked inside a production speech stack with other engineers. I ask for the failure case early and prefer experiments you can re-run." },
      { id: "weak", keys: ["weakness", "weaknesses", "improve", "growth", "challenge", "hardest"], src: "Profile",
        a: "I can over-invest in getting the evaluation story right before shipping a rough prototype. I am getting better at landing a thin vertical slice first, then deepening the probes once something runs end to end." },
      { id: "study", keys: ["study", "book", "module", "learn", "learning", "shelf", "drive", "blog", "blogs", "case study", "case studies", "writing", "meraki", "poem", "poems", "poetry"], src: "Writing and Library tabs",
        a: "Meraki is my poetry journal (An Alleyway to Sonder) ,  open it from the Writing tab, or the full site at srivastavadya.wixsite.com/meraki14. Study notes live in the Library tab. Non-ML case studies and decks are under Other work." },
      { id: "contact", keys: ["contact", "email", "reach", "resume", "cv", "github", "linkedin", "hello"], src: "Resume",
        a: "You can email srivastavadya@gmail.com, find code at github.com/Adya6714, or download the resume with the button at the top of the page." }
    ],
    fallback: "I'm not sure I have a good answer for that one. Email me at srivastavadya@gmail.com, or try one of the interview threads above."
  }
};
