// Builds api/kb.js (the guardian's knowledge base) from js/content.js.
// Run after editing content: node tools/make_kb.js
const fs = require("fs"), path = require("path"), vm = require("vm");
const root = path.join(__dirname, "..");
const sandbox = { window: {} };
vm.runInNewContext(fs.readFileSync(path.join(root, "js/content.js"), "utf8"), sandbox);
const C = sandbox.window.CONTENT;
const L = [];
const P = C.person;
const aboutText = [P.line, ...(P.aboutIntro || []), ...(P.aboutCore || []), P.about].filter(Boolean).join("\n");
L.push(`# About ${P.name}`, aboutText, `Status: ${P.status}`, `Email: ${P.email}`, `GitHub: ${P.github}`, `LinkedIn: ${P.linkedin}`, "");
L.push("# Papers");
C.papers.forEach(p => L.push(`- ${p.title} [${p.status}]: ${p.note} ${p.links.map(l => l[1]).join(" ")}`));
L.push("", "# Research notes (results)");
C.notes.forEach(n => L.push(`## ${n.title} (${n.project})`, `Question: ${n.q}`, `Result: ${n.found}`, `Why it matters: ${n.why}`, ""));
L.push("# Projects");
C.projects.forEach(p => L.push(`## ${p.title}`, p.line, `Problem: ${p.problem}`, `Built: ${p.built.join(" ")}`, `Impact: ${p.impact}`, `Links: ${p.links.map(l => l[1]).join(" ") || "none"}`, ""));
L.push("# Experience");
C.jobs.forEach(j => L.push(`## ${j.co}: ${j.role}, ${j.when}`, ...j.pts.map(x => `- ${x}`), ""));
L.push("# Skills");
C.skills.forEach(([g, items]) => L.push(`- ${g}: ${items.map(i => `${i[0]} (used in ${i[1]})`).join(", ")}`));
L.push("", "# Education", "B.E. Electrical and Electronics Engineering, BITS Pilani, 2026, minor in Finance.");
const out = "// Generated by tools/make_kb.js from js/content.js. Do not edit by hand.\nmodule.exports = " + JSON.stringify(L.join("\n")) + ";\n";
fs.writeFileSync(path.join(root, "api/kb.js"), out);
console.log("api/kb.js written,", out.length, "chars");
