// Builds api/kb.js (the guardian's knowledge base) from js/content.js + js/interview.js.
// Run after editing content: npm run kb
const fs = require("fs"), path = require("path"), vm = require("vm");
const root = path.join(__dirname, "..");
const sandbox = { window: {} };
vm.runInNewContext(fs.readFileSync(path.join(root, "js/content.js"), "utf8"), sandbox);
const interviewPath = path.join(root, "js/interview.js");
if (fs.existsSync(interviewPath)) {
  vm.runInNewContext(fs.readFileSync(interviewPath, "utf8"), sandbox);
}
const C = sandbox.window.CONTENT;
const L = [];
const P = C.person || {};
const aboutText = [
  ...(P.intro || []),
  ...(P.closing || []),
  ...(P.aboutIntro || []),
  ...(P.aboutCore || []),
  P.about, P.line
].filter(Boolean).join("\n");
L.push(`# About ${P.name || "Adya"}`, aboutText, `Email: ${P.email || ""}`, `GitHub: ${P.github || ""}`, `LinkedIn: ${P.linkedin || ""}`, "");

if (C.research) {
  L.push("# Research threads");
  C.research.forEach(r => {
    L.push(`## ${r.title || r.label}`, r.headline || "", r.blurb || r.summary || "", "");
  });
}
if (C.notes) {
  L.push("# Research notes");
  C.notes.forEach(n => L.push(`## ${n.title} (${n.project})`, `Question: ${n.q}`, `Result: ${n.found}`, `Why it matters: ${n.why}`, ""));
}
if (C.papers) {
  L.push("# Papers");
  C.papers.forEach(p => L.push(`- ${p.title} [${p.status}]: ${p.note || ""}`));
  L.push("");
}

L.push("# Projects");
(C.projects || []).forEach(p => {
  const links = p.links ? (Array.isArray(p.links) ? p.links.map(l => Array.isArray(l) ? l[1] : (l.url || l)).join(" ") : Object.values(p.links).filter(Boolean).join(" ")) : "";
  L.push(`## ${p.title}`, p.line || "", p.problem ? `Problem: ${p.problem}` : "", p.built ? `Built: ${(p.built || []).join("; ")}` : "", p.impact ? `Impact: ${p.impact}` : "", links ? `Links: ${links}` : "", "");
});

L.push("# Experience");
(C.jobs || []).forEach(j => L.push(`## ${j.co}: ${j.role}, ${j.when}`, ...(j.pts || []).map(x => `- ${x}`), ""));

L.push("# Skills");
(C.skills || []).forEach(([g, items]) => {
  const list = (items || []).map(i => Array.isArray(i) ? i[0] : i).join(", ");
  L.push(`- ${g}: ${list}`);
});

const IV = C.interview;
if (IV && IV.tracks) {
  L.push("", "# Interview answers");
  IV.tracks.forEach(t => {
    L.push(`## Track: ${t.name}`);
    (t.questions || []).forEach(q => {
      L.push(`### ${q.q}`, `Short: ${q.short || ""}`, q.long ? `Long: ${q.long}` : "", q.challenge ? `Challenge: ${q.challenge}` : "", "");
    });
  });
}

L.push("", "# Education", "B.E. Electrical and Electronics Engineering, BITS Pilani, 2026, minor in Finance.");
const text = L.join("\n");
const out = "// Generated by tools/make_kb.js from js/content.js (+ interview.js). Do not edit by hand.\nmodule.exports = " + JSON.stringify(text) + ";\n";
fs.writeFileSync(path.join(root, "api/kb.js"), out);
fs.writeFileSync(path.join(root, "api/kb.mjs"), "// Generated by tools/make_kb.js\nexport default " + JSON.stringify(text) + ";\n");
fs.mkdirSync(path.join(root, "worker"), { recursive: true });
fs.writeFileSync(path.join(root, "worker/kb.mjs"), "// Generated by tools/make_kb.js\nexport default " + JSON.stringify(text) + ";\n");
console.log("api/kb.js + api/kb.mjs + worker/kb.mjs written,", out.length, "chars");
